import * as THREE from './vendor/three.module.min.js';
import { createArt } from './art.js?v=visual-04';
import { createCharacter } from './character.js?v=visual-04';
import { createTools } from './tools.js?v=visual-04';
import { createMouseLook } from './mouse-look.js?v=mouse-05';

const M=window.RoomModel, $=id=>document.getElementById(id), KEY='afterhours.3d.v2';
let s=M.fresh(),canSave=true;
try{const old=JSON.parse(localStorage.getItem(KEY));const loaded=M.migrate(old);if(loaded){s=loaded;s.player.vx=s.player.vz=0;}}catch{canSave=false;}
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('failure').hidden=false;$('failureText').textContent='WebGL 2 could not start. Try enabling hardware acceleration or opening this page in another modern browser.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;$('world').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#14232d');scene.fog=new THREE.Fog('#14232d',35,75);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100),target=new THREE.Vector3(0,0,-1);
let yaw=0,pitch=.24,distance=4.2,follow=true,cameraBoom=4.2;
scene.add(new THREE.HemisphereLight('#b0cfdf','#534331',1.12));
const sun=new THREE.DirectionalLight('#d3dfe4',2.5);sun.position.set(-8,14,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-16,right:16,top:16,bottom:-16,near:.5,far:45});sun.shadow.bias=-.0005;sun.shadow.normalBias=.022;sun.shadow.radius=3;scene.add(sun);
const art=createArt(scene,renderer);
const materials=new Map();
function mat(color,roughness=.75,metalness=0){const key=color+roughness+metalness;if(!materials.has(key))materials.set(key,Object.assign(art.surfaceMat(color,metalness?'metal':'paint').clone(),{roughness,metalness}));return materials.get(key);}
const boxGeo=new THREE.BoxGeometry(1,1,1);
function box(parent,x,y,z,w,h,d,color,shadow=true){const o=new THREE.Mesh(boxGeo,typeof color==='string'?mat(color):color);o.position.set(x,y,z);o.scale.set(w,h,d);o.castShadow=shadow;o.receiveShadow=true;parent.add(o);return o;}
function cylinder(parent,x,y,z,r,h,color){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,16),mat(color));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function label(parent,words,x,y,z,w,h,color='#e7d4b6',bg='#253b49',font=44){const c=document.createElement('canvas');c.width=512;c.height=words.includes('|')?256:96;const g=c.getContext('2d');g.fillStyle=bg;g.fillRect(0,0,512,c.height);g.fillStyle=color;g.textAlign='center';g.textBaseline='middle';g.font=`bold ${font}px system-ui`;words.split('|').forEach((line,i,a)=>g.fillText(line,256,c.height/2+(i-(a.length-1)/2)*65));const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tex}));mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
function lineLoop(points,color,parent=scene){const geometry=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p)));const line=new THREE.LineLoop(geometry,new THREE.LineBasicMaterial({color}));parent.add(line);return line;}
box(scene,0,-.33,-1,18.4,.6,20.4,'#243342');box(scene,0,-.025,-1,17.6,.08,19.6,'#586369');
const wallMats=[Object.assign(art.surfaceMat('#59606a','plaster').clone(),{transparent:true}),Object.assign(art.surfaceMat('#59606a','plaster').clone(),{transparent:true})];
box(scene,0,1.7,-10.8,18,3.4,.28,'#405361');box(scene,-8.9,1.7,-1,.25,3.4,19.5,wallMats[0]);box(scene,8.9,1.7,-1,.25,3.4,19.5,wallMats[1]);
box(scene,0,.09,8.8,18,.18,.2,'#b0917d');box(scene,-8.73,.15,-1,.12,.3,19.5,'#af8f7a');box(scene,8.73,.15,-1,.12,.3,19.5,'#af8f7a');
const partitionMat=Object.assign(art.surfaceMat('#557078','plaster').clone(),{transparent:true});
box(scene,-5.65,1.5,-5,6.7,3,.28,partitionMat);box(scene,5.65,1.5,-5,6.7,3,.28,partitionMat);box(scene,0,2.85,-5,4.65,.3,.3,'#a9aaa0');
for(const x of [-2.35,2.35])box(scene,x,1.5,-5,.15,3,.4,'#b4aa92');
const wallPanel=box(scene,0,1.6,-10.6,16,2.1,.1,art.surfaceMat('#45616a','plaster'));
label(scene,'BACK STORAGE  /  WORKSHOP',0,2.4,-10.51,6,.8,'#e1d2aa','#314953',31);
// Workshop furniture, shelves, paint tins, and a rolling trolley.
box(scene,7.55,.95,-9.8,1.6,.16,1.1,'#bd9873');for(const x of [6.9,8.15])box(scene,x,.46,-9.8,.09,.9,.8,'#384956');
for(let i=0;i<4;i++)cylinder(scene,7+i%2*.43,1.2,-9.8+Math.floor(i/2)*.35,.14,.35,['#bd8d9c','#76ada1','#d8b46f','#8395ba'][i]);
for(let i=0;i<3;i++){box(scene,-7.7,.5+i*.8,-10,1.3,.1,.8,'#9b8771');box(scene,-7.7,.72+i*.8,-10,.7,.4,.55,'#b5a17e');}
box(scene,-7,.3,7.2,1.1,.6,.7,'#6e7a75');box(scene,-7,.64,7.2,1.2,.08,.8,'#bca782');
const bays=[];for(let i=0;i<3;i++){const b=M.bays[i];const l=lineLoop([[b.x-1.1,.02,b.z-1],[b.x+1.1,.02,b.z-1],[b.x+1.1,.02,b.z+1],[b.x-1.1,.02,b.z+1]],'#b0cfad');bays.push(l);const lab=label(scene,`BAY 0${i+1}`,b.x,.025,b.z+1.4,1.7,.55,'#c3d1b3','#43565d',48);lab.rotation.x=-Math.PI/2;}
art.decorate();
// Architectural finish: ceiling coffers, aged brass trim, sconces and a warmer threshold.
for(const z of [-8.8,-5.1,-1.3,2.5,6.3]){box(scene,0,3.46,z,17.55,.11,.12,'#24363e');for(const x of [-8.15,8.15])box(scene,x,2.45,z,.09,1.9,.09,'#a8875d');}
for(const [x,z,turn] of [[-8.69,-2.4,Math.PI/2],[8.69,-2.4,-Math.PI/2],[-8.69,4.5,Math.PI/2],[8.69,4.5,-Math.PI/2]]){const fixture=new THREE.Group();fixture.position.set(x,2.25,z);fixture.rotation.y=turn;scene.add(fixture);box(fixture,0,0,0,.06,.42,.2,'#8f7552');const bulb=new THREE.Mesh(new THREE.SphereGeometry(.09,16,12),new THREE.MeshBasicMaterial({color:'#ffd7a0'}));bulb.position.x=.11;fixture.add(bulb);const light=new THREE.PointLight('#ffc883',4.5,4.5,2);light.position.set(x+(x<0?.18:-.18),2.2,z);scene.add(light);}
const threshold=box(scene,0,.075,8.62,4.8,.05,.18,'#b89762');threshold.material=art.surfaceMat('#b89762','metal');
label(scene,'EST. 1987  •  PLAY AGAIN',0,3.05,-10.42,5.4,.32,'#c5ad7e','#263d46',25);
const palette=[['#30465c','#c6aa94'],['#b17a8d','#e2c8b1'],['#57948b','#dcc699'],['#8e664b','#b18c66']],wallColors=['#456c71','#795664','#bdad8e','#414e76'],cabColors=['#73bdb1','#d398ac','#d8b46a','#9297cb'];
const floorBatches=Array.from({length:4},()=>{const batch=new THREE.InstancedMesh(new THREE.BoxGeometry(.885,.055,1.135),mat('#817970'),M.COUNT);batch.receiveShadow=true;batch.frustumCulled=false;scene.add(batch);return batch;});
const grime=new THREE.InstancedMesh(new THREE.PlaneGeometry(1.25,1.4),new THREE.MeshStandardMaterial({map:art.dirtMap,transparent:true,opacity:.9,roughness:1,depthWrite:false}),M.COUNT);scene.add(grime);
const dust=new THREE.InstancedMesh(new THREE.BoxGeometry(.16,.045,.085),mat('#c5b494'),M.COUNT*4);dust.castShadow=true;scene.add(dust);const tmp=new THREE.Object3D();
const fxCount=220,fxPos=new Float32Array(fxCount*3),fxColor=new Float32Array(fxCount*3),fxVelocity=Array.from({length:fxCount},()=>new THREE.Vector3()),fxLife=new Float32Array(fxCount);let fxCursor=0;
const fxGeo=new THREE.BufferGeometry();fxGeo.setAttribute('position',new THREE.BufferAttribute(fxPos,3));fxGeo.setAttribute('color',new THREE.BufferAttribute(fxColor,3));const workFx=new THREE.Points(fxGeo,new THREE.PointsMaterial({size:.075,vertexColors:true,transparent:true,opacity:.82,depthWrite:false,sizeAttenuation:true}));workFx.frustumCulled=false;scene.add(workFx);
function emitWorkFx(amount=1){const wall=s.stage===4,color=new THREE.Color(s.stage===1?'#d7ba88':s.stage===2?'#96d4d2':s.stage===3&&s.floorPhase===0?'#9b8d78':s.stage===3?'#e8d7ae':s.stage===4&&s.wallPhase===2?wallColors[s.wall]:'#d7c6a8');for(let j=0;j<Math.min(28,5+amount*4);j++){const i=fxCursor++%fxCount,a=Math.random()*Math.PI*2,r=Math.random()*.65;fxPos[i*3]=s.player.x+Math.cos(a)*r;fxPos[i*3+1]=wall?.5+Math.random()*2.2:.08+Math.random()*.18;fxPos[i*3+2]=s.player.z+Math.sin(a)*r;fxColor.set([color.r,color.g,color.b],i*3);fxVelocity[i].set((Math.random()-.5)*(wall?.35:1.1),.35+Math.random()*(wall?.55:1.4),(Math.random()-.5)*(wall?.35:1.1));fxLife[i]=.45+Math.random()*.75;}fxGeo.attributes.position.needsUpdate=fxGeo.attributes.color.needsUpdate=true;}
function updateWorkFx(dt){for(let i=0;i<fxCount;i++){if(fxLife[i]<=0){fxPos[i*3+1]=-20;continue;}fxLife[i]-=dt;fxVelocity[i].y-=dt*(s.stage===2?.15:1.25);fxPos[i*3]+=fxVelocity[i].x*dt;fxPos[i*3+1]+=fxVelocity[i].y*dt;fxPos[i*3+2]+=fxVelocity[i].z*dt;}fxGeo.attributes.position.needsUpdate=true;workFx.material.opacity=.58+.18*Math.sin(performance.now()*.008);}
const cabinetGroups=[],cabinetBodies=[],screens=[];
function buildCabinet(i){const c=art.cabinet(i,i===0?cabColors[s.color]:i===1?'#bca075':'#9c8fac');c.group.userData.cabinet=i;scene.add(c.group);cabinetGroups.push(c.group);cabinetBodies.push(c.body);screens.push(c.screen);return c.group;}
for(let i=0;i<3;i++)buildCabinet(i);
const machineStains=cabinetGroups.map(group=>{const stains=[];for(let j=0;j<3;j++){const stain=new THREE.Mesh(new THREE.PlaneGeometry(j===2?.9:.95,j===1?.6:.8),new THREE.MeshStandardMaterial({map:art.dirtMap,transparent:true,opacity:.8,depthWrite:false,roughness:1}));stain.position.set(j===2?.721:0,j===0?.55:j===1?1.65:1.25,j===0?.69:j===1?.55:0);if(j===2)stain.rotation.y=Math.PI/2;stain.userData.cleanStain=true;group.add(stain);stains.push(stain);}return stains;});
// A small, fully modelled character with animated arms and legs.
const character=createCharacter(art),avatar=character.root;scene.add(avatar);
const toolKit=createTools(art),tool=toolKit.root;scene.add(tool);const handPosition=new THREE.Vector3();
const dolly=new THREE.Group();scene.add(dolly);box(dolly,0,.12,0,1.35,.1,1.35,'#537e8b');for(const x of [-.62,.62]){const w=cylinder(dolly,x,.12,.3,.13,.12,'#1e303c');w.rotation.z=Math.PI/2;box(dolly,x,.55,-.5,.05,.8,.05,'#84a6aa');}box(dolly,0,.97,-.5,1.25,.055,.05,'#84a6aa');art.tube(dolly,[[-.6,.2,-.5],[-.6,1.02,-.5],[-.5,1.12,-.5],[.5,1.12,-.5],[.6,1.02,-.5],[.6,.2,-.5]],.025,'#89a1a0');art.box(dolly,0,1.12,-.5,.55,.075,.065,'#273939',.018);
const targetRing=new THREE.Mesh(new THREE.RingGeometry(.25,.32,32),new THREE.MeshBasicMaterial({color:'#b9f0cd',side:THREE.DoubleSide}));targetRing.rotation.x=-Math.PI/2;targetRing.position.y=.1;scene.add(targetRing);targetRing.visible=false;
const glow=new THREE.PointLight('#91efd1',0,6,2);glow.position.set(0,2,0);scene.add(glow);
const wallpaperCanvas=document.createElement('canvas');wallpaperCanvas.width=128;wallpaperCanvas.height=256;const wg=wallpaperCanvas.getContext('2d');wg.fillStyle='#76695a';wg.fillRect(0,0,128,256);wg.fillStyle='#a5947d';for(let x=0;x<128;x+=32)wg.fillRect(x,0,2,256);wg.strokeStyle='#b1a186';wg.lineWidth=2;for(let y=16;y<256;y+=48){wg.beginPath();wg.ellipse(64,y,11,18,0,0,7);wg.stroke();}const wallpaperMap=new THREE.CanvasTexture(wallpaperCanvas);wallpaperMap.colorSpace=THREE.SRGBColorSpace;const wallpaperMaterial=new THREE.MeshStandardMaterial({map:wallpaperMap,roughness:1});
const wallSections=[],wallScars=[];for(let i=0;i<16;i++){const w=M.wallTile(i);wallSections.push(box(scene,w.x,1.68,w.z,.06,2.25,1.5,'#685856'));const scar=new THREE.Line(new THREE.BufferGeometry().setFromPoints(Array.from({length:7},(_,j)=>new THREE.Vector3(w.x+(i<8?.04:-.04),1.3+j*.11+Math.sin(j*2+i)*.04,w.z+(j%2?.06:-.05)))),new THREE.LineBasicMaterial({color:'#574d43',transparent:true}));scene.add(scar);wallScars.push(scar);}
const rubble=new THREE.InstancedMesh(new THREE.BoxGeometry(.6,.09,.75),mat('#9c8b71'),M.COUNT);rubble.castShadow=true;rubble.receiveShadow=true;scene.add(rubble);
const binFill=box(scene,-7,.58,7.2,.9,.3,.55,'#978671');label(scene,'FLOORING / DISPOSAL',-7,1.05,7.24,1.75,.35,'#ecdabc','#314c4b',30);
const debrisBag=new THREE.Group();avatar.add(debrisBag);art.box(debrisBag,-.44,.58,-.28,.45,.72,.42,'#827759',.08);art.tube(debrisBag,[[-.4,.75,-.27],[-.33,1.25,-.19],[.15,1.27,-.19]],.035,'#716344');
let path=[],autoAction=null,keys=new Set(),working=false,orbit=false,pointerDown=null,last=performance.now(),lastSave=0,workClock=0,walkPhase=0,lastStage=s.stage,toastUntil=0,muted=true,audio=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(s));$('save').textContent='Saved on this device';}catch{canSave=false;$('save').textContent='Session only · storage unavailable';}}
function tone(f=500){if(muted)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.2);}catch{}}
function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;toastUntil=performance.now()+3500;}
function phase(){return s.stage+':'+s.floorPhase+':'+s.wallPhase;}
let lastPhase=phase();
let showUnfinished=false;
const workHints=new THREE.InstancedMesh(new THREE.RingGeometry(.52,.555,4),new THREE.MeshBasicMaterial({color:'#f3bf61',side:THREE.DoubleSide,transparent:true,opacity:.9,depthTest:false,depthWrite:false}),M.COUNT);
workHints.renderOrder=8;workHints.frustumCulled=false;scene.add(workHints);
function updateWorkHints(){
 const left=M.remaining(s),key=M.workKey(s);workHints.count=left.length;workHints.visible=left.length>0&&(showUnfinished||left.length<=12);
 left.forEach((i,j)=>{const q=s.stage===4?M.wallTile(i):M.tile(i);tmp.position.set(q.x,s.stage===4?1.68:.105,q.z);tmp.rotation.set(s.stage===4?0:-Math.PI/2,s.stage===4?Math.PI/2:0,Math.PI/4);tmp.scale.set(s.stage===4?2.75:1,s.stage===4?1.9:1.3,1);tmp.updateMatrix();workHints.setMatrixAt(j,tmp.matrix);});workHints.instanceMatrix.needsUpdate=true;
 $('inspect').hidden=!left.length;$('inspect').setAttribute('aria-pressed',String(showUnfinished));$('inspect').textContent=showUnfinished?'Hide outlines':'Show unfinished';
 $('findWork').hidden=!left.length&&!(s.stage===3&&s.floorPhase===1&&s.load);
 $('findWork').textContent=s.stage===3&&s.floorPhase===1&&(s.load===12||!left.length)?'Empty debris bag':`Find next patch · ${left.length} left`;
 if(key)$('count').textContent=`${M.percent(s)}% complete · ${left.length} ${s.stage===4?'wall sections':'patches'} left`;
}
$('inspect').onclick=()=>{showUnfinished=!showUnfinished;updateWorkHints();};
$('findWork').onclick=()=>{
 stop();if(!$('journal').hidden)$('journalToggle').click();
 if(s.stage===3&&s.floorPhase===1&&(s.load===12||!M.remaining(s).length)){navigate(-6,6.5);toast('Walk to the disposal bin, then press E to empty the bag.');return;}
 const left=M.remaining(s).map(i=>({i,...(s.stage===4?M.wallTile(i):M.tile(i))})).sort((a,b)=>Math.hypot(a.x-s.player.x,a.z-s.player.z)-Math.hypot(b.x-s.player.x,b.z-s.player.z));
 if(left[0]){const q=left[0];showUnfinished=true;updateWorkHints();navigate(s.stage===4?q.x+(q.i<8?.95:-.95):q.x,s.stage===4?q.z:q.z);toast('Heading to unfinished work. Hold Work when you arrive.');}
};
function taskTitle(){return s.stage===3?['Lift the old floor.','Nothing left behind.','Lay it piece by piece.'][s.floorPhase]:s.stage===4?['Strip the tired walls.','Make good the plaster.','A fresh coat, by hand.'][s.wallPhase]:s.stage===5&&s.machineDirt.some(a=>a.some(Boolean))?'A little care for every machine.':titles[s.stage];}
function taskDescription(){return s.stage===3?['Hold Work near each tile to pry it loose. Lifted pieces stay on the floor until collected.','Press E near loose flooring to collect it. Carry up to 12 pieces to the disposal bin by the front left corner, then E to empty it.','Choose a finish in the journal. Hold Work over each bare section to install the new floor.'][s.floorPhase]:s.stage===4?['Walk along both side walls. Hold Work to strip each wallpaper section.','Hold Work close to each stripped wall section to fill and sand its damaged plaster.','Choose a color, then hold Work beside every prepared wall section to paint it.'][s.wallPhase]:s.stage===5&&s.machineDirt.some(a=>a.some(Boolean))?'Visit all three machines in storage. Press E for a close-up and rub away the dirt by hand before opening Star Signal’s service panel.':descriptions[s.stage];}
function toolName(){return s.stage===3?['Pry bar','Debris bag · '+s.load+'/12','Tile setter'][s.floorPhase]:s.stage===4?['Wallpaper scraper','Plaster trowel','Paint roller'][s.wallPhase]:['Hand truck','Broom','Mop','','','Cleaning cloth / service kit','Hand truck','Drive-belt gauge','Hand truck','Arcade controls','Grow-light tester','Hand truck','Arcade controls','Free exploration'][s.stage];}
const titles=['Make a little room.','A clean sweep.','Under all that grime.','A floor worth dancing on.','A fresh coat.','Follow the signal.','Bring it home.','Tune Moon Rally.','Bring out the racer.','Road test.','Wake the garden.','Bring out the garden.','Let it grow.','Opening night.'];
const descriptions=['Move all three cabinets safely into storage.','Sweep the main floor section by section.','Mop every patch of grime.','','','Reconnect Star Signal’s circuit.','Return Star Signal to the arcade.','Set Moon Rally’s three drive belts to the marked tensions.','Wheel Moon Rally onto the restored floor.','Play a road test to commission Moon Rally.','Restore Pixel Garden’s nine grow lights.','Wheel Pixel Garden onto the restored floor.','Play a growth cycle to commission Pixel Garden.','All three cabinets are restored and ready for free play.'];
const stepNames=['Store three cabinets','Sweep loose debris','Mop the grime','Lift old flooring','Bag and dispose of debris','Lay new flooring','Strip old wallpaper','Patch damaged walls','Paint each wall section','Hand-clean all three machines','Rewire Star Signal','Return Star Signal','Tune Moon Rally drive belts','Return Moon Rally','Road-test Moon Rally','Restore Pixel Garden grow lights','Return Pixel Garden','Run Pixel Garden growth cycle'];
function jobIndex(){return s.stage<3?s.stage:s.stage===3?3+s.floorPhase:s.stage===4?6+s.wallPhase:s.stage===5?(s.machineDirt.flat().some(v=>v>0)?9:10):s.stage===6?11:s.stage===7?12:s.stage===8?13:s.stage===9?14:s.stage===10?15:s.stage===11?16:s.stage===12?17:18;}
function button(t,fn){const b=document.createElement('button');b.textContent=t;b.onclick=fn;return b;}
function swatches(label,key,names,colors){const l=document.createElement('label');l.textContent=label;$('options').append(l);const row=document.createElement('div');row.className='swatches';names.forEach((n,i)=>{const b=button(n,()=>{s[key]=i;refresh();save();});b.style.setProperty('--swatch',colors[i]);b.setAttribute('aria-pressed',String(s[key]===i));row.append(b);});$('options').append(row);}
function refresh(){const stage=s.stage;$('resumeStatus').textContent=stage>=7?'Your saved game has its first corner restored. Restart from beginning to experience every renovation job.':'Saved restoration: '+taskTitle()+' Use Restart from beginning for a fresh abandoned arcade.';$('enter').textContent=stage===0&&M.progress(s)===0?'Open the arcade':'Continue restoration';$('title').textContent=taskTitle();$('description').textContent=taskDescription();$('objective').textContent=taskTitle()+' · '+M.percent(s)+'%';$('progress').style.width=M.progress(s)*100+'%';$('count').textContent=stage===0?`${s.cabinets.filter(c=>c.stored).length} / 3 cabinets parked`:stage<6?`${M.percent(s)}% complete`:stage===13?'ARCADE RESTORED':'RESTORATION STEP '+(jobIndex()+1)+' OF 18';$('tool').textContent=toolName();$('work').disabled=!M.workKey(s);$('work').textContent=working?'Work ON · click to stop':'Space · Work';$('work').setAttribute('aria-pressed',String(working));$('options').replaceChildren();
if(stage===3&&s.floorPhase===2||stage>=7)swatches('FLOOR','palette',['Midnight','Candy','Seaside','Parquet'],palette.map(p=>p[0]));if(stage===4&&s.wallPhase===2||stage>=7){swatches('WALLS','wall',['Teal','Rose','Cream','Ink'],wallColors);}if(stage>=5)swatches('STAR SIGNAL','color',['Mint','Rose','Honey','Lilac'],cabColors);
if(stage===3&&s.floorPhase===1)$('options').append(button('Walk to disposal bin',()=>navigate(-6,6.5,'park')));
$('steps').replaceChildren();stepNames.forEach((n,i)=>{const li=document.createElement('li');li.textContent=(i<jobIndex()?'✓ ':`${i+1}. `)+n;li.className=i<jobIndex()?'done':'';$('steps').append(li);});
floorBatches.forEach((batch,b)=>batch.material=art.floorMaterial(b<2?(b===0?'#aba18b':'#929282'):palette[s.palette][b-2],b<2?'old':s.palette===3?'parquet':s.palette===0?'terrazzo':'tile'));
for(let i=0;i<M.COUNT;i++){const floorPosition=M.tile(i),batchIndex=s.floor[i]>=1?2+(i%17+Math.floor(i/17))%2:(i%3?0:1);tmp.position.set(floorPosition.x,.035,floorPosition.z);tmp.rotation.set(0,0,0);floorBatches.forEach((batch,b)=>{tmp.scale.setScalar(b===batchIndex&&(s.removed[i]<1||s.floor[i]>=1)?1:0);tmp.updateMatrix();batch.setMatrixAt(i,tmp.matrix);});const t=M.tile(i);tmp.position.set(t.x+Math.sin(i*17)*.17,.071,t.z+Math.cos(i*13)*.14);tmp.rotation.set(-Math.PI/2,0,i);tmp.scale.setScalar((s.grime[i]>0?Math.max(.3,s.grime[i]):0)*(.52+(i*71%19)*.045));tmp.updateMatrix();grime.setMatrixAt(i,tmp.matrix);for(let j=0;j<4;j++){tmp.position.set(t.x+((i*7+j*13)%9-4)*.075,.11,t.z+((i*11+j*7)%11-5)*.07);tmp.rotation.set(0,i+j,0);tmp.scale.setScalar(s.dust[i]>0?Math.max(.35,s.dust[i]):0);tmp.updateMatrix();dust.setMatrixAt(i*4+j,tmp.matrix);}}grime.instanceMatrix.needsUpdate=true;dust.instanceMatrix.needsUpdate=true;floorBatches.forEach(b=>b.instanceMatrix.needsUpdate=true);
wallPanel.material=mat(stage>=5?wallColors[s.wall]:'#45616a');partitionMat.color.set(stage>=5?wallColors[s.wall]:'#557078');wallMats.forEach(m=>m.color.set(stage>=5?wallColors[s.wall]:'#59606a'));wallSections.forEach((o,i)=>{o.material=s.wallStrip[i]<1?wallpaperMaterial:art.surfaceMat(s.wallPaint[i]>=1?wallColors[s.wall]:s.wallPatch[i]>=1?'#dfd4ba':'#958c7d','plaster');o.scale.y=2.25;wallScars[i].visible=s.wallPatch[i]<1;wallScars[i].material.opacity=1-s.wallPatch[i];});for(let i=0;i<M.COUNT;i++){const q=M.tile(i);tmp.position.set(q.x,.12,q.z);tmp.rotation.set(.08,i*.7,.04);tmp.scale.setScalar(s.loose[i]?1:0);tmp.updateMatrix();rubble.setMatrixAt(i,tmp.matrix);}rubble.instanceMatrix.needsUpdate=true;binFill.scale.y=.15+s.load/12*.45;cabinetBodies[0].color.set(cabColors[s.color]);art.refresh(s);machineStains.forEach((stains,i)=>stains.forEach(stain=>stain.material.opacity=s.machineDirt[i].reduce((a,v)=>a+v,0)/24*.85));toolKit.select(s);updateWorkHints();if(!canSave)$('save').textContent='Session only · storage unavailable';}
function stop(){mouseLook.release();keys.clear();working=false;path=[];autoAction=null;s.player.vx=s.player.vz=0;orbit=false;pointerDown=null;mini.left=mini.right=false;refresh();}
function changed(){if(lastPhase!==phase()){working=false;path=[];autoAction=null;keys.clear();lastPhase=phase();toast(taskDescription());}if(lastStage!==s.stage){working=false;path=[];autoAction=null;keys.clear();toast(['','Space to breathe. Broom unlocked.','Found a brass token. Keep it for the first game.','The old floor is clean. Time to lift it.','New flooring down. Strip the side walls next.','Visit all three machines for hand cleaning.','It lives! Bring Star Signal back to the room.','The first light is on. Welcome back.'][s.stage]);tone(400+s.stage*80);lastStage=s.stage;}refresh();save();}
function interact(){path=[];autoAction=null;const result=M.interact(s);if(result==='clean'){openClean(M.nearest(s));}else if(['collected','unloaded','disposed','full','empty'].includes(result)){toast({collected:'Collected. Bag: '+s.load+' / 12',unloaded:'Debris emptied. Back for the next load.',disposed:'All old flooring disposed. Ready to install.',full:'Bag full. Take it to the disposal bin.',empty:'Your debris bag is empty.'}[result]);}else if(result==='repair'){stop();renderWires();$('repair').showModal();}else if(result==='play')openGame();else if(result==='loaded')toast([6,8,11].includes(s.stage)?'Loaded. Bring the restored cabinet onto the main floor; E parks it.':'Hand truck loaded. Walk to storage; E parks the cabinet.');else if(result==='stored')toast('Parked safely in storage.');else if(result==='nearer')toast(s.stage===3?'Walk closer to loose flooring or the disposal bin.':'Walk closer to a cabinet first.');else if(result==='unavailable')toast('This cabinet is waiting for a later restoration.');else if(result==='dropped')toast('Cabinet set down. E loads it again.');changed();}
function navigate(x,z,action=null){document.getElementById("world").focus();path=M.path(s,x,z);autoAction=action;if(path.length){targetRing.position.set(path.at(-1).x,.1,path.at(-1).z);targetRing.visible=true;}else{autoAction=null;if(Math.hypot(s.player.x-x,s.player.z-z)>.7)toast('That spot is blocked. Try an open patch of floor.');}}
const mouseLook=createMouseLook({element:renderer.domElement,canLock:()=>follow&&!modal()&&$('journal').hidden&&!document.hidden,onLook:(x,y)=>{yaw-=x*.0025;pitch=THREE.MathUtils.clamp(pitch+y*.002,-.12,.6);},onRelease:()=>{keys.clear();working=false;path=[];autoAction=null;orbit=false;pointerDown=null;s.player.vx=s.player.vz=0;refresh();},onChange:locked=>{$('reticle').hidden=!locked;$('mouseLock').textContent=locked?'Esc · Release mouse':'Mouse look';$('mouseLock').setAttribute('aria-pressed',String(locked));},onError:()=>{$('mouseLock').title='Free mouse look: move to look, hold near either side to keep turning. Escape releases the mouse.';toast('Free mouse look enabled · no dragging needed · screen edges keep turning · Esc releases');}});
$('mouseLock').onclick=()=>{if(mouseLook.active())mouseLook.release();else{if(!$('journal').hidden)$('journalToggle').click();mouseLook.request();}};
new MutationObserver(()=>{if(modal()||!$('journal').hidden)mouseLook.release();}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['open','hidden']});
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==2)return;$('world').focus();if(mouseLook.active()){if(e.button===0&&M.workKey(s)){working=true;refresh();}return;}if(follow&&e.pointerType==='mouse'&&e.button===0){if(!$('journal').hidden)$('journalToggle').click();mouseLook.request();return;}pointerDown={x:e.clientX,y:e.clientY,button:e.button};orbit=e.button===2;renderer.domElement.setPointerCapture(e.pointerId);});
renderer.domElement.addEventListener('pointermove',e=>{if(orbit&&!mouseLook.active()){yaw-=e.movementX*.006;pitch=THREE.MathUtils.clamp(pitch+e.movementY*.004,follow?-.12:.35,follow?.6:1.25);}});
renderer.domElement.addEventListener('pointerup',e=>{if(mouseLook.active()){if(e.button===0){working=false;refresh();}return;}if(follow&&e.pointerType==='mouse'&&e.button===0)return;const start=pointerDown;orbit=false;pointerDown=null;if(!start||start.button!==0||Math.hypot(start.x-e.clientX,start.y-e.clientY)>12)return;keys.clear();pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(cabinetGroups,true);if(hits.length&&s.held<0){let o=hits[0].object;while(o&&o.userData.cabinet===undefined)o=o.parent;const i=o?.userData.cabinet;if(i!==undefined){const c=s.cabinets[i];if(M.nearest(s)===i){interact();return;}navigate(c.x,c.z+1.75,i);return;}}
if(raycaster.ray.intersectPlane(ground,hit))navigate(hit.x,hit.z,s.held>=0&&(hit.z< -6.3||[6,8,11].includes(s.stage)&&hit.z> -3.5)?'park':null);});
document.addEventListener('pointerup',e=>{if(e.button===0&&working&&mouseLook.active()&&!e.target.closest('button')){working=false;refresh();}});
renderer.domElement.addEventListener('pointercancel',()=>{orbit=false;pointerDown=null;working=false;refresh();});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance+e.deltaY*(follow?.003:.012),follow?2:9,follow?5:34);},{passive:false});
function modal(){return !!document.querySelector('dialog[open]');}
window.addEventListener('keydown',e=>{if(modal()||((e.key===' '||e.key==='Enter')&&e.target.closest('button,summary')))return;const k=e.key.toLowerCase();if(!$('journal').hidden&&!['j','c','escape'].includes(k))return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','e','q','r','j','c','escape'].includes(k)){e.preventDefault();if(k==='j'&&!e.repeat)$('journalToggle').click();else if(k==='c'&&!e.repeat)$('camera').click();else if(k==='e'&&!e.repeat)interact();else if(k==='escape'){stop();if(!$('journal').hidden)$('journalToggle').click();refresh();}else{keys.add(k);if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){path=[];autoAction=null;}}}});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{stop();if(mini.running){mini.running=false;$('score').textContent='Paused. Press Play for a new round.';}refresh();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();mini.running=false;save();refresh();}});
$('interact').onclick=interact;$('work').onclick=()=>{working=!working;refresh();$('world').focus();};$('camera').onclick=()=>{stop();follow=!follow;distance=follow?4.2:28;pitch=follow?.24:.73;$('camera').textContent=follow?'Room camera':'Chase camera';};$('home').onclick=()=>{yaw=follow?0:.52;pitch=follow?.24:.73;distance=follow?4.2:28;};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'Sound off':'Sound on';$('sound').setAttribute('aria-pressed',String(!muted));tone();};$('journalToggle').onclick=()=>{stop();$('journal').hidden=!$('journal').hidden;$('journalToggle').textContent=$('journal').hidden?'Show journal':'Hide journal';$('objective').hidden=!$('journal').hidden;};$('help').onclick=()=>{stop();$('welcome').showModal();};$('enter').onclick=()=>{$('welcome').close();$('world').focus();toast(taskDescription());if(matchMedia('(pointer:fine)').matches)mouseLook.request();};function showRestart(){stop();if(!$('welcome').open)$('welcome').showModal();$('confirm').hidden=false;$('confirm').scrollIntoView({block:'nearest'});$('yes').focus();}
$('restart').onclick=showRestart;$('new').onclick=showRestart;$('no').onclick=()=>$('confirm').hidden=true;$('yes').onclick=()=>{s=M.fresh();lastStage=0;stop();yaw=0;pitch=.24;distance=4.2;cameraBoom=4.2;follow=true;$('camera').textContent='Room camera';$('journal').hidden=false;$('journalToggle').textContent='Hide journal';$('objective').hidden=true;$('confirm').hidden=true;changed();$('welcome').close();$('world').focus();};
document.querySelectorAll('[data-dir]').forEach(b=>{const k={up:'w',down:'s',left:'a',right:'d'}[b.dataset.dir];b.onpointerdown=e=>{e.preventDefault();path=[];autoAction=null;keys.add(k);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(k);});
let repairingCabinet=0;
function openRepair(i){repairingCabinet=i;renderWires();$('repair').showModal();}
function renderWires(){const row=$('wires');row.replaceChildren();const names=['STAR SIGNAL / SERVICE PANEL','MOON RALLY / DRIVE BAY','PIXEL GARDEN / GROW ARRAY'];const heads=['Follow the signal.','Balance the drive belts.','Light the whole garden.'];const copy=['Rotate the connectors to join the signal path.','Cycle each belt tension until its needle sits on the painted service mark.','Toggle a grow light and its neighbors until every lamp is glowing.'];$('repairEyebrow').textContent=names[repairingCabinet];$('repairTitle').textContent=heads[repairingCabinet];$('repairCopy').textContent=copy[repairingCabinet];
 if(repairingCabinet===0)s.wires.forEach((rot,i)=>{const b=button('',()=>{s.wires[i]=(s.wires[i]+1)%4;renderWires();save();tone(300);});b.innerHTML=`<svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="32" fill="#263d4d"/><path d="M50 0 V50 H100" fill="none" stroke="#a1e5c7" stroke-width="10" transform="rotate(${rot*90} 50 50)"/></svg>`;row.append(b);});
 else if(repairingCabinet===1)s.moon.forEach((v,i)=>{const b=button(`BELT ${i+1}\n${['LOOSE','LOW','MARK','TIGHT'][v]}`,()=>{s.moon[i]=(v+1)%4;renderWires();save();tone(220+v*70);});b.className='puzzle-button';row.append(b);});
 else s.pixel.forEach((v,i)=>{const b=button(v?'✦':'·',()=>{[i,i-3,i+3,i%3?i-1:-1,i%3<2?i+1:-1].filter(j=>j>=0&&j<9).forEach(j=>s.pixel[j]=s.pixel[j]?0:1);renderWires();save();tone(v?180:520);});b.className='puzzle-button';b.setAttribute('aria-pressed',String(!!v));row.append(b);});
 $('wireStatus').textContent=repairingCabinet===0?'Six connectors. One continuous path.':repairingCabinet===1?'Service marks: 2 · 1 · 3':'All nine grow lights must glow together.';}
$('closeRepair').onclick=()=>$('repair').close();$('hint').onclick=()=>{$('wireStatus').textContent=repairingCabinet===0?'Input → down → right → up → right → down → output.':repairingCabinet===1?'The painted marks read 2 · 1 · 3.':'Press the four corner lamps and the center lamp.';};$('test').onclick=()=>{if(M.repair(s,repairingCabinet)){$('repair').close();changed();}else{$('wireStatus').textContent='The cabinet still fails its service check. Inspect every setting.';tone(130);}};
let cleaningCabinet=0,clothDown=false,cleanRenderer=null,cleanBase=null,cleanMode='dust',cleanCursor={x:410,y:315,visible:false},cleanFeedback='';
const cleanPass=v=>v>.67?'dust':v>.33?'wash':'polish';
function drawCleaningHand(){if(!cleanCursor.visible)return;const {x,y}=cleanCursor;cg.save();cg.translate(x,y);cg.rotate(-.35);cg.shadowColor='#0008';cg.shadowBlur=9;cg.fillStyle='#d2a07f';cg.beginPath();cg.roundRect(-3,5,62,31,15);cg.fill();cg.fillStyle='#eadfca';cg.beginPath();cg.roundRect(-25,-18,47,42,9);cg.fill();cg.strokeStyle='#9fb5ae';cg.lineWidth=3;cg.stroke();cg.fillStyle='#bf896d';for(let i=0;i<4;i++){cg.beginPath();cg.roundRect(9+i*9,-3,9,30,5);cg.fill();}cg.restore();}
function setCleanMode(mode){cleanMode=mode;cleanFeedback='';document.querySelectorAll('[data-clean]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.clean===mode)));drawClean();}
document.querySelectorAll('[data-clean]').forEach(b=>b.onclick=()=>setCleanMode(b.dataset.clean));
function cabinetCloseup(){try{cleanRenderer??=new THREE.WebGLRenderer({antialias:true,alpha:true});cleanRenderer.setSize(480,360);cleanRenderer.setClearColor('#172932',0);cleanRenderer.outputColorSpace=THREE.SRGBColorSpace;cleanRenderer.toneMapping=THREE.ACESFilmicToneMapping;const view=new THREE.Scene();view.add(new THREE.HemisphereLight('#d5e6df','#433727',2));const light=new THREE.DirectionalLight('#ffe6bd',3);light.position.set(-2,4,4);view.add(light);const model=cabinetGroups[cleaningCabinet].clone(true);model.position.set(0,0,0);model.rotation.set(0,0,0);model.traverse(o=>{if(o.userData.cleanStain)o.visible=false;});view.add(model);const lens=new THREE.PerspectiveCamera(46,480/360,.05,20);lens.position.set(.06,1.38,2.15);lens.lookAt(0,1.4,.3);cleanRenderer.render(view,lens);cleanBase=document.createElement('canvas');cleanBase.width=480;cleanBase.height=360;cleanBase.getContext('2d').drawImage(cleanRenderer.domElement,0,0);}catch{cleanBase=null;}}

const cloth=$('cloth'),cg=cloth.getContext('2d');
function drawClean(){cg.fillStyle='#162832';cg.fillRect(0,0,480,360);cg.fillStyle=cabColors[cleaningCabinet===0?s.color:cleaningCabinet===1?2:3];cg.fillRect(40,15,400,335);cg.fillStyle='#e6d4ac';cg.font='bold 22px monospace';cg.textAlign='center';cg.fillText(['STAR SIGNAL','MOON RALLY','PIXEL GARDEN'][cleaningCabinet],240,48);cg.fillStyle='#0b1924';cg.fillRect(70,65,340,166);cg.strokeStyle='#93c9bb';cg.lineWidth=3;cg.strokeRect(88,81,304,130);cg.fillStyle='#456b6f';cg.fillRect(62,243,356,52);cg.fillStyle='#dcb09d';for(let i=0;i<3;i++){cg.beginPath();cg.arc(280+i*38,267,11,0,7);cg.fill();}cg.fillStyle='#d9c397';cg.beginPath();cg.arc(140,262,15,0,7);cg.fill();cg.fillStyle='#28343a';cg.fillRect(200,307,80,35);if(cleanBase){cg.fillStyle='#182b32';cg.fillRect(0,0,480,360);cg.drawImage(cleanBase,0,0);}s.machineDirt[cleaningCabinet].forEach((v,i)=>{if(!v)return;const x=(i%6)*80,y=Math.floor(i/6)*90;cg.save();cg.beginPath();cg.rect(x,y,80,90);cg.clip();cg.fillStyle='rgba(107,93,66,'+(v*.22)+')';cg.fillRect(x,y,80,90);cg.globalAlpha=Math.max(.3,v)*.9;cg.drawImage(art.dirtMap.image,x-25,y-30,140,160);cg.globalAlpha=Math.max(.3,v)*.4;cg.drawImage(art.dirtMap.image,x+10,y+15,85,90);cg.restore();if(s.machineDirt[cleaningCabinet].filter(Boolean).length<=4){cg.strokeStyle='#f3bf61';cg.lineWidth=2;cg.strokeRect(x+3,y+3,74,84);}});drawCleaningHand();const dirty=s.machineDirt[cleaningCabinet].filter(Boolean).length;Array.from($('patches').children).forEach((b,i)=>{b.disabled=!s.machineDirt[cleaningCabinet][i];b.textContent='Patch '+(i+1)+(b.disabled?' · clean':' · needs cleaning');});$('cleanStatus').textContent=(dirty?Math.min(99,Math.floor((1-s.machineDirt[cleaningCabinet].reduce((a,v)=>a+v,0)/24)*100)):100)+'% clean · '+(s.machineDirt[cleaningCabinet].some(Boolean)?dirty+(dirty===1?' patch':' patches')+' left · '+(cleanFeedback||('Use '+({dust:'Dust',wash:'Scrub',polish:'Polish'}[cleanPass(Math.max(...s.machineDirt[cleaningCabinet]))])+'.')):'Clean and ready.');}
function openClean(i){stop();cleaningCabinet=i;cleanMode='dust';cleanCursor.visible=false;cabinetCloseup();$('cleanTitle').textContent=['Star Signal','Moon Rally','Pixel Garden'][i]+' · hand cleaning';$('patches').replaceChildren();for(let p=0;p<24;p++){$('patches').append(button('Patch '+(p+1),()=>{const needed=cleanPass(s.machineDirt[i][p]);if(cleanMode!==needed){cleanFeedback='Choose '+({dust:'Dust',wash:'Scrub',polish:'Polish'}[needed])+' for that patch.';}else M.wipe(s,i,p,cleanMode);drawClean();changed();}));}setCleanMode('dust');$('clean').showModal();}
function rub(e){const r=cloth.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*480,y=(e.clientY-r.top)/r.height*360;cleanCursor={x,y,visible:true};if(clothDown){let changedPatch=false,wrong='';for(let i=0;i<24;i++){const px=(i%6)*80+40,py=Math.floor(i/6)*90+45;if(Math.hypot(px-x,py-y)<54){const needed=cleanPass(s.machineDirt[cleaningCabinet][i]);if(s.machineDirt[cleaningCabinet][i]&&needed!==cleanMode)wrong=needed;else changedPatch=M.wipe(s,cleaningCabinet,i,cleanMode)||changedPatch;}}cleanFeedback=wrong?'That area needs '+({dust:'dusting',wash:'scrubbing',polish:'polishing'}[wrong])+'.':changedPatch?'Good—keep working across the surface.':'';if(changedPatch){refresh();save();}}drawClean();}
cloth.onpointerdown=e=>{clothDown=true;cloth.setPointerCapture(e.pointerId);rub(e);};cloth.onpointermove=rub;cloth.onpointerleave=()=>{if(!clothDown){cleanCursor.visible=false;drawClean();}};cloth.onpointerup=cloth.onpointercancel=()=>clothDown=false;$('closeClean').onclick=()=>{$('clean').close();clothDown=false;cleanCursor.visible=false;changed();};$('clean').addEventListener('close',()=>{clothDown=false;cleanCursor.visible=false;});

const mini={running:false,type:0,x:270,time:0,score:0,stars:[],spawn:0,left:false,right:false,commissioned:false},screen=$('screen'),g=screen.getContext('2d');
function openGame(i=0){stop();mini.type=i;mini.running=false;const names=['STAR SIGNAL','MOON RALLY','PIXEL GARDEN'];$('gameTitle').textContent=names[i];$('gameCopy').textContent=i===0?'Catch 12 stars in 30 seconds.':i===1?'Steer between lanes and collect 8 moon flags. Avoid the warning cones.':'Guide the watering beam to 8 seedlings before the cycle ends.';$('score').textContent=`Best: ${s.best[i]}. Ready when you are.`;$('game').showModal();screen.focus();}
$('closeGame').onclick=()=>{$('game').close();mini.running=false;};$('game').addEventListener('close',()=>{mini.running=false;mini.left=mini.right=false;});$('start').onclick=()=>{Object.assign(mini,{running:true,x:270,time:30,score:0,stars:[],spawn:0,left:false,right:false,commissioned:false});screen.focus();};screen.onpointermove=e=>{const r=screen.getBoundingClientRect();mini.x=THREE.MathUtils.clamp((e.clientX-r.left)/r.width*540,30,510);mini.left=mini.right=false;};screen.onpointerdown=screen.onpointermove;screen.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();mini[e.key==='ArrowLeft'?'left':'right']=true;}};screen.onkeyup=e=>mini[e.key==='ArrowLeft'?'left':'right']=false;screen.onblur=()=>{mini.left=mini.right=false;};
function miniFrame(dt){if(!$('game').open)return;const colors=[['#10273d','#07111d'],['#3a2448','#120f25'],['#173d35','#071c20']][mini.type];const bg=g.createLinearGradient(0,0,0,340);bg.addColorStop(0,colors[0]);bg.addColorStop(1,colors[1]);g.fillStyle=bg;g.fillRect(0,0,540,340);g.strokeStyle='#ffffff20';for(let x=90;x<540;x+=90){g.beginPath();g.moveTo(x,0);g.lineTo(x,340);g.stroke();}if(mini.running){mini.time-=dt;mini.spawn-=dt;mini.x=THREE.MathUtils.clamp(mini.x+((mini.right?1:0)-(mini.left?1:0))*360*dt,30,510);if(mini.spawn<=0){mini.stars.push({x:45+Math.random()*450,y:-20,bad:mini.type===1&&Math.random()<.3});mini.spawn=mini.type===0?.6:.72;}for(const q of mini.stars){q.y+=(mini.type===1?155:125)*dt;if(q.y>275&&q.y<325&&Math.abs(q.x-mini.x)<38){if(!q.bad){mini.score++;tone(650);}else{mini.score=Math.max(0,mini.score-1);tone(120);}q.y=400;}}mini.stars=mini.stars.filter(q=>q.y<360);const goal=mini.type===0?12:8;$('score').textContent=`${mini.score} / ${goal} · ${Math.max(0,Math.ceil(mini.time))} seconds`;if(mini.type>0&&!mini.commissioned&&mini.score>=goal){mini.commissioned=true;M.commission(s,mini.type);changed();$('score').textContent=`Commissioning passed! ${mini.score} / ${goal}`;}if(mini.time<=0){mini.running=false;s.best[mini.type]=Math.max(s.best[mini.type],mini.score);save();$('score').textContent=`${mini.score>=goal?'Cabinet ready!':'Try again!'} Score ${mini.score} · Best ${s.best[mini.type]}`;}}
 g.textAlign='center';g.font='24px system-ui';for(const q of mini.stars){g.fillStyle=q.bad?'#ff765f':mini.type===0?'#eddbab':mini.type===1?'#e8b8ff':'#83e39d';g.fillText(q.bad?'▲':mini.type===0?'✦':mini.type===1?'⚑':'♣',q.x,q.y);}g.fillStyle=mini.type===0?'#9edfc3':mini.type===1?'#f4a6d7':'#77d99a';g.beginPath();g.roundRect(mini.x-34,305,68,14,5);g.fill();if(mini.type===1){g.fillStyle='#f4d36d';g.fillRect(mini.x-18,292,36,18);}if(!mini.running){g.font='bold 27px monospace';g.fillStyle='#e1d4ae';g.fillText(['STAR SIGNAL','MOON RALLY','PIXEL GARDEN'][mini.type],270,150);}g.fillStyle='#030b1625';for(let y=0;y<340;y+=3)g.fillRect(0,y,540,1);}const markerButtons=[];
function updateMarkers(){
  const items=[];
  if(s.held>=0){const b=M.bays[s.held];items.push({name:[6,8,11].includes(s.stage)?'Place on restored floor':'Park in storage',x:[6,8,11].includes(s.stage)?0:b.x,z:[6,8,11].includes(s.stage)?2:-7.8,y:.4,fn:()=>navigate([6,8,11].includes(s.stage)?0:b.x,[6,8,11].includes(s.stage)?2:-7.8,'park')});}
  else if(s.stage===3&&s.floorPhase===1){items.push({name:'Empty debris bag · '+s.load+'/12',x:-7,z:7.2,y:1.1,fn:()=>navigate(-6,6.5,'park')});}else if(s.stage===0||s.stage>=5){s.cabinets.forEach((c,i)=>{if((s.stage===0&&!c.stored)||(s.stage===5&&(s.machineDirt[i].some(Boolean)||i===0))||(s.stage===6&&i===0)||(s.stage>=7&&s.stage<=9&&i===1)||(s.stage>=10&&s.stage<=12&&i===2)||(s.stage===13&&s.repaired[i]))items.push({name:['Star Signal','Moon Rally','Pixel Garden'][i],x:c.x,z:c.z,y:2.8,fn:()=>{if(M.nearest(s)===i)interact();else navigate(c.x,c.z+1.75,i);}});});}
  while(markerButtons.length<items.length){const b=button('',()=>{});$('markers').append(b);markerButtons.push(b);}
  markerButtons.forEach((b,i)=>{const item=items[i];b.hidden=!item;if(!item)return;const p=new THREE.Vector3(item.x,item.y,item.z).project(camera);b.hidden=p.z>1||p.z< -1||Math.abs(p.x)>1||Math.abs(p.y)>1;b.textContent=item.name;b.onclick=item.fn;b.style.left=(p.x*.5+.5)*innerWidth+'px';b.style.top=(-p.y*.5+.5)*innerHeight+'px';});
}
let statFrames=0,statTime=performance.now();
let stalled=0;
function frame(now){const dt=Math.min((now-last)/1000,.04);last=now;mouseLook.update(dt);if(!document.hidden&&!modal()){
if(keys.has('q'))yaw+=dt;if(keys.has('r'))yaw-=dt;let dx=0,dz=0;const right=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),forward=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0);
if(right||forward){dx=Math.cos(yaw)*right-Math.sin(yaw)*forward;dz=-Math.sin(yaw)*right-Math.cos(yaw)*forward;}else if(path.length){while(path.length&&Math.hypot(path[0].x-s.player.x,path[0].z-s.player.z)<.19)path.shift();if(path.length){dx=path[0].x-s.player.x;dz=path[0].z-s.player.z;}else{s.player.vx=s.player.vz=0;if(autoAction!==null){const action=autoAction;autoAction=null;if(action==='park'||M.nearest(s)===action)interact();}}}
const ox=s.player.x,oz=s.player.z;M.step(s,dx,dz,dt);if(follow)s.player.yaw=yaw+Math.PI;if(path.length&&Math.hypot(s.player.x-ox,s.player.z-oz)<.001){stalled+=dt;if(stalled>1){path=[];autoAction=null;stalled=0;toast('A tight spot. Try backing up or setting the cabinet down.');}}else stalled=0;
if((working||keys.has(' '))&&M.workKey(s)){workClock+=dt;if(workClock>.12){workClock=0;const before=phase(),n=M.work(s);if(n||phase()!==before){if(n)emitWorkFx(n);changed();tone(s.stage===1?180:300);}}}if(now-lastSave>2000){save();lastSave=now;}}
walkPhase+=Math.hypot(s.player.vx||0,s.player.vz||0)*dt*2.5;avatar.position.set(s.player.x,0,s.player.z);avatar.rotation.y=s.player.yaw;character.animate({dt,shortTool:s.stage===3&&s.floorPhase===2,speed:Math.hypot(s.player.vx||0,s.player.vz||0),phase:walkPhase,time:now,working:working||keys.has(' '),hauling:s.held>=0,tool:!!M.workKey(s),wall:s.stage===4,side:s.player.x<0?-1:1});avatar.updateMatrixWorld(true);character.rightHand.getWorldPosition(handPosition);debrisBag.visible=s.stage===3&&s.floorPhase===1&&s.load>0;tool.visible=!!M.workKey(s);const grip=toolKit.grip(),lean=.34,spread=Math.sin(lean)*grip;tool.position.set(handPosition.x+Math.cos(s.player.yaw)*spread,handPosition.y-Math.cos(lean)*grip,handPosition.z-Math.sin(s.player.yaw)*spread);tool.rotation.set(.08+(working||keys.has(' ')?Math.sin(now*.012)*.08:0),s.player.yaw,lean);
s.cabinets.forEach((c,i)=>{cabinetGroups[i].position.set(c.x,s.held===i?.13:0,c.z);cabinetGroups[i].rotation.y=c.yaw;});dolly.visible=s.held>=0;if(dolly.visible){const c=s.cabinets[s.held];dolly.position.set(c.x,0,c.z);dolly.rotation.y=c.yaw;}
glow.intensity=s.repaired[0]?8:0;glow.position.set(s.cabinets[0].x,1.7,s.cabinets[0].z+.8);targetRing.visible=path.length>0;targetRing.rotation.z=now*.001;
if(follow){const cp=M.cameraPosition(s,yaw,distance,pitch),allowed=Math.hypot(cp.x-s.player.x,cp.z-s.player.z);cameraBoom=Math.min(allowed,THREE.MathUtils.lerp(cameraBoom,allowed,1-Math.exp(-5*dt)));const ratio=allowed?cameraBoom/allowed:0;cp.x=s.player.x+(cp.x-s.player.x)*ratio;cp.z=s.player.z+(cp.z-s.player.z)*ratio;cp.y=1.65+(cp.y-1.65)*ratio;avatar.visible=Math.hypot(cp.x-s.player.x,cp.z-s.player.z)>1.8;camera.position.set(cp.x,cp.y,cp.z);camera.lookAt(s.player.x-Math.sin(yaw)*3,1.25-Math.sin(pitch)*2,s.player.z-Math.cos(yaw)*3);wallMats.forEach(m=>m.opacity=1);partitionMat.opacity=1;}else{avatar.visible=true;const desired=new THREE.Vector3(0,.6,-1);target.lerp(desired,1-Math.exp(-4*dt));camera.position.set(target.x+Math.sin(yaw)*Math.cos(pitch)*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(target);wallMats[0].opacity=camera.position.x<0?.12:.9;wallMats[1].opacity=camera.position.x>0?.12:.9;partitionMat.opacity=.22;}

const near=M.nearest(s);$('interact').textContent=s.stage===3&&s.floorPhase===1?'E · Collect / empty':s.held>=0?'E · Park cabinet':near>=0?(s.stage===5?'E · Clean / repair':((s.stage===9&&near===1)||(s.stage===12&&near===2)||s.stage===13&&s.repaired[near])?'E · Play':'E · Load cabinet'):'E · Interact';$('context').textContent=mouseLook.active()?'Mouse to look · WASD to move · E interact · hold click / Space to work · J journal · Esc cursor':follow?'Click the scene for mouse look · WASD to move · J journal · C room view':s.held>=0?'Pull the cabinet through the wide doorway · E to park':path.length?'Walking… WASD takes control':M.workKey(s)?'Hold Work on one section · right-drag to look · journal for details':near>=0?'E to interact · right-drag to look around':'WASD to walk · click floor to walk · right-drag to orbit';if(now>toastUntil)$('toast').style.opacity=0;
updateMarkers();updateWorkFx(dt);art.animate(now);miniFrame(dt);renderer.render(scene,camera);statFrames++;if(now-statTime>1500){$('renderStats').textContent=`${Math.round(statFrames*1000/(now-statTime))} FPS · ${renderer.info.render.calls} draw calls · ${Math.round(renderer.info.render.triangles/1000)}k triangles · ${renderer.getPixelRatio().toFixed(2)}× resolution`;statFrames=0;statTime=now;}requestAnimationFrame(frame);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});window.addEventListener('pagehide',save);refresh();$('welcome').showModal();$('enter').focus();requestAnimationFrame(frame);
