import * as THREE from './vendor/three.module.min.js';
import { createArt } from './art.js';
import { createCharacter } from './character.js?v=restoration-02';
import { createTools } from './tools.js';
import { createMouseLook } from './mouse-look.js?v=mouse-05';

const M=window.RoomModel, $=id=>document.getElementById(id), KEY='afterhours.3d.v2';
let s=M.fresh(),canSave=true;
try{const old=JSON.parse(localStorage.getItem(KEY));const loaded=M.migrate(old);if(loaded){s=loaded;s.player.vx=s.player.vz=0;}}catch{canSave=false;}
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('failure').hidden=false;$('failureText').textContent='WebGL 2 could not start. Try enabling hardware acceleration or opening this page in another modern browser.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;$('world').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#14232d');scene.fog=new THREE.Fog('#14232d',35,75);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100),target=new THREE.Vector3(0,0,-1);
let yaw=0,pitch=.24,distance=4.2,follow=true,cameraBoom=4.2;
scene.add(new THREE.HemisphereLight('#b0cfdf','#534331',1.12));
const sun=new THREE.DirectionalLight('#d3dfe4',2.5);sun.position.set(-8,14,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-16,right:16,top:16,bottom:-16,near:.5,far:45});sun.shadow.bias=-.0005;sun.shadow.normalBias=.022;sun.shadow.radius=3;scene.add(sun);
const art=createArt(scene,renderer);
const materials=new Map();
function mat(color,roughness=.75,metalness=0){const key=color+roughness+metalness;if(!materials.has(key))materials.set(key,Object.assign(art.surfaceMat(color,metalness?'metal':'paint').clone(),{roughness,metalness}));return materials.get(key);}
const boxGeo=new THREE.BoxGeometry(1,1,1);
function box(parent,x,y,z,w,h,d,color,shadow=true){const o=new THREE.Mesh(boxGeo,typeof color==='string'?mat(color):color);o.position.set(x,y,z);o.scale.set(w,h,d);o.castShadow=shadow;o.receiveShadow=true;parent.add(o);return o;}
function cylinder(parent,x,y,z,r,h,color){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,16),mat(color));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function label(parent,words,x,y,z,w,h,color='#e7d4b6',bg='#253b49',font=44){const c=document.createElement('canvas');c.width=512;c.height=words.includes('|')?256:96;const g=c.getContext('2d');g.fillStyle=bg;g.fillRect(0,0,512,c.height);g.fillStyle=color;g.textAlign='center';g.textBaseline='middle';g.font=`bold ${font}px system-ui`;words.split('|').forEach((line,i,a)=>g.fillText(line,256,c.height/2+(i-(a.length-1)/2)*65));const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tex}));mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
function lineLoop(points,color,parent=scene){const geometry=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p)));const line=new THREE.LineLoop(geometry,new THREE.LineBasicMaterial({color}));parent.add(line);return line;}
box(scene,0,-.33,-1,18.4,.6,20.4,'#243342');box(scene,0,-.025,-1,17.6,.08,19.6,'#586369');
const wallMats=[Object.assign(art.surfaceMat('#59606a').clone(),{transparent:true}),Object.assign(art.surfaceMat('#59606a').clone(),{transparent:true})];
box(scene,0,1.7,-10.8,18,3.4,.28,'#405361');box(scene,-8.9,1.7,-1,.25,3.4,19.5,wallMats[0]);box(scene,8.9,1.7,-1,.25,3.4,19.5,wallMats[1]);
box(scene,0,.09,8.8,18,.18,.2,'#b0917d');box(scene,-8.73,.15,-1,.12,.3,19.5,'#af8f7a');box(scene,8.73,.15,-1,.12,.3,19.5,'#af8f7a');
const partitionMat=Object.assign(art.surfaceMat('#557078').clone(),{transparent:true});
box(scene,-5.65,1.5,-5,6.7,3,.28,partitionMat);box(scene,5.65,1.5,-5,6.7,3,.28,partitionMat);box(scene,0,2.85,-5,4.65,.3,.3,'#a9aaa0');
for(const x of [-2.35,2.35])box(scene,x,1.5,-5,.15,3,.4,'#b4aa92');
const wallPanel=box(scene,0,1.6,-10.6,16,2.1,.1,'#45616a');
label(scene,'BACK STORAGE  /  WORKSHOP',0,2.4,-10.51,6,.8,'#e1d2aa','#314953',31);
// Workshop furniture, shelves, paint tins, and a rolling trolley.
box(scene,7.55,.95,-9.8,1.6,.16,1.1,'#bd9873');for(const x of [6.9,8.15])box(scene,x,.46,-9.8,.09,.9,.8,'#384956');
for(let i=0;i<4;i++)cylinder(scene,7+i%2*.43,1.2,-9.8+Math.floor(i/2)*.35,.14,.35,['#bd8d9c','#76ada1','#d8b46f','#8395ba'][i]);
for(let i=0;i<3;i++){box(scene,-7.7,.5+i*.8,-10,1.3,.1,.8,'#9b8771');box(scene,-7.7,.72+i*.8,-10,.7,.4,.55,'#b5a17e');}
box(scene,-7,.3,7.2,1.1,.6,.7,'#6e7a75');box(scene,-7,.64,7.2,1.2,.08,.8,'#bca782');
const bays=[];for(let i=0;i<3;i++){const b=M.bays[i];const l=lineLoop([[b.x-1.1,.02,b.z-1],[b.x+1.1,.02,b.z-1],[b.x+1.1,.02,b.z+1],[b.x-1.1,.02,b.z+1]],'#b0cfad');bays.push(l);const lab=label(scene,`BAY 0${i+1}`,b.x,.025,b.z+1.4,1.7,.55,'#c3d1b3','#43565d',48);lab.rotation.x=-Math.PI/2;}
art.decorate();
const palette=[['#30465c','#c6aa94'],['#b17a8d','#e2c8b1'],['#57948b','#dcc699'],['#8e664b','#b18c66']],wallColors=['#456c71','#795664','#bdad8e','#414e76'],cabColors=['#73bdb1','#d398ac','#d8b46a','#9297cb'];
const floorBatches=Array.from({length:4},()=>{const batch=new THREE.InstancedMesh(new THREE.BoxGeometry(.885,.055,1.135),mat('#817970'),M.COUNT);batch.receiveShadow=true;batch.frustumCulled=false;scene.add(batch);return batch;});
const grime=new THREE.InstancedMesh(new THREE.PlaneGeometry(1.25,1.4),new THREE.MeshStandardMaterial({map:art.dirtMap,transparent:true,opacity:.9,roughness:1,depthWrite:false}),M.COUNT);scene.add(grime);
const dust=new THREE.InstancedMesh(new THREE.BoxGeometry(.16,.045,.085),mat('#c5b494'),M.COUNT*4);dust.castShadow=true;scene.add(dust);const tmp=new THREE.Object3D();
const cabinetGroups=[],cabinetBodies=[],screens=[];
function buildCabinet(i){const c=art.cabinet(i,i===0?cabColors[s.color]:i===1?'#bca075':'#9c8fac');c.group.userData.cabinet=i;scene.add(c.group);cabinetGroups.push(c.group);cabinetBodies.push(c.body);screens.push(c.screen);return c.group;}
for(let i=0;i<3;i++)buildCabinet(i);
const machineStains=cabinetGroups.map(group=>{const stains=[];for(let j=0;j<3;j++){const stain=new THREE.Mesh(new THREE.PlaneGeometry(j===2?.9:.95,j===1?.6:.8),new THREE.MeshStandardMaterial({map:art.dirtMap,transparent:true,opacity:.8,depthWrite:false,roughness:1}));stain.position.set(j===2?.721:0,j===0?.55:j===1?1.65:1.25,j===0?.69:j===1?.55:0);if(j===2)stain.rotation.y=Math.PI/2;stain.userData.cleanStain=true;group.add(stain);stains.push(stain);}return stains;});
// A small, fully modelled character with animated arms and legs.
const character=createCharacter(art),avatar=character.root;scene.add(avatar);
const toolKit=createTools(art),tool=toolKit.root;avatar.add(tool);tool.position.set(.33,.15,.62);
const dolly=new THREE.Group();scene.add(dolly);box(dolly,0,.12,0,1.35,.1,1.35,'#537e8b');for(const x of [-.62,.62]){const w=cylinder(dolly,x,.12,.3,.13,.12,'#1e303c');w.rotation.z=Math.PI/2;box(dolly,x,.55,-.5,.05,.8,.05,'#84a6aa');}box(dolly,0,.97,-.5,1.25,.055,.05,'#84a6aa');art.tube(dolly,[[-.6,.2,-.5],[-.6,1.02,-.5],[-.5,1.12,-.5],[.5,1.12,-.5],[.6,1.02,-.5],[.6,.2,-.5]],.025,'#89a1a0');art.box(dolly,0,1.12,-.5,.55,.075,.065,'#273939',.018);
const targetRing=new THREE.Mesh(new THREE.RingGeometry(.25,.32,32),new THREE.MeshBasicMaterial({color:'#b9f0cd',side:THREE.DoubleSide}));targetRing.rotation.x=-Math.PI/2;targetRing.position.y=.1;scene.add(targetRing);targetRing.visible=false;
const glow=new THREE.PointLight('#91efd1',0,6,2);glow.position.set(0,2,0);scene.add(glow);
const wallpaperCanvas=document.createElement('canvas');wallpaperCanvas.width=128;wallpaperCanvas.height=256;const wg=wallpaperCanvas.getContext('2d');wg.fillStyle='#76695a';wg.fillRect(0,0,128,256);wg.fillStyle='#a5947d';for(let x=0;x<128;x+=32)wg.fillRect(x,0,2,256);wg.strokeStyle='#b1a186';wg.lineWidth=2;for(let y=16;y<256;y+=48){wg.beginPath();wg.ellipse(64,y,11,18,0,0,7);wg.stroke();}const wallpaperMap=new THREE.CanvasTexture(wallpaperCanvas);wallpaperMap.colorSpace=THREE.SRGBColorSpace;const wallpaperMaterial=new THREE.MeshStandardMaterial({map:wallpaperMap,roughness:1});
const wallSections=[],wallScars=[];for(let i=0;i<16;i++){const w=M.wallTile(i);wallSections.push(box(scene,w.x,1.68,w.z,.06,2.25,1.5,'#685856'));const scar=new THREE.Line(new THREE.BufferGeometry().setFromPoints(Array.from({length:7},(_,j)=>new THREE.Vector3(w.x+(i<8?.04:-.04),1.3+j*.11+Math.sin(j*2+i)*.04,w.z+(j%2?.06:-.05)))),new THREE.LineBasicMaterial({color:'#574d43',transparent:true}));scene.add(scar);wallScars.push(scar);}
const rubble=new THREE.InstancedMesh(new THREE.BoxGeometry(.6,.09,.75),mat('#9c8b71'),M.COUNT);rubble.castShadow=true;rubble.receiveShadow=true;scene.add(rubble);
const binFill=box(scene,-7,.58,7.2,.9,.3,.55,'#978671');label(scene,'FLOORING / DISPOSAL',-7,1.05,7.24,1.75,.35,'#ecdabc','#314c4b',30);
const debrisBag=new THREE.Group();avatar.add(debrisBag);art.box(debrisBag,-.44,.58,-.28,.45,.72,.42,'#827759',.08);art.tube(debrisBag,[[-.4,.75,-.27],[-.33,1.25,-.19],[.15,1.27,-.19]],.035,'#716344');
let path=[],autoAction=null,keys=new Set(),working=false,orbit=false,pointerDown=null,last=performance.now(),lastSave=0,workClock=0,walkPhase=0,lastStage=s.stage,toastUntil=0,muted=true,audio=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(s));$('save').textContent='Saved on this device';}catch{canSave=false;$('save').textContent='Session only · storage unavailable';}}
function tone(f=500){if(muted)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.2);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.2);}catch{}}
function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;toastUntil=performance.now()+3500;}
function phase(){return s.stage+':'+s.floorPhase+':'+s.wallPhase;}
let lastPhase=phase();
let showUnfinished=false;
const workHints=new THREE.InstancedMesh(new THREE.RingGeometry(.52,.555,4),new THREE.MeshBasicMaterial({color:'#f3bf61',side:THREE.DoubleSide,transparent:true,opacity:.9,depthTest:false,depthWrite:false}),M.COUNT);
workHints.renderOrder=8;workHints.frustumCulled=false;scene.add(workHints);
function updateWorkHints(){
 const left=M.remaining(s),key=M.workKey(s);workHints.count=left.length;workHints.visible=left.length>0&&(showUnfinished||left.length<=12);
 left.forEach((i,j)=>{const q=s.stage===4?M.wallTile(i):M.tile(i);tmp.position.set(q.x,s.stage===4?1.68:.105,q.z);tmp.rotation.set(s.stage===4?0:-Math.PI/2,s.stage===4?Math.PI/2:0,Math.PI/4);tmp.scale.set(s.stage===4?2.75:1,s.stage===4?1.9:1.3,1);tmp.updateMatrix();workHints.setMatrixAt(j,tmp.matrix);});workHints.instanceMatrix.needsUpdate=true;
 $('inspect').hidden=!left.length;$('inspect').setAttribute('aria-pressed',String(showUnfinished));$('inspect').textContent=showUnfinished?'Hide outlines':'Show unfinished';
 $('findWork').hidden=!left.length&&!(s.stage===3&&s.floorPhase===1&&s.load);
 $('findWork').textContent=s.stage===3&&s.floorPhase===1&&(s.load===12||!left.length)?'Empty debris bag':`Find next patch · ${left.length} left`;
 if(key)$('count').textContent=`${M.percent(s)}% complete · ${left.length} ${s.stage===4?'wall sections':'patches'} left`;
}
$('inspect').onclick=()=>{showUnfinished=!showUnfinished;updateWorkHints();};
$('findWork').onclick=()=>{
 stop();if(!$('journal').hidden)$('journalToggle').click();
 if(s.stage===3&&s.floorPhase===1&&(s.load===12||!M.remaining(s).length)){navigate(-6,6.5);toast('Walk to the disposal bin, then press E to empty the bag.');return;}
 const left=M.remaining(s).map(i=>({i,...(s.stage===4?M.wallTile(i):M.tile(i))})).sort((a,b)=>Math.hypot(a.x-s.player.x,a.z-s.player.z)-Math.hypot(b.x-s.player.x,b.z-s.player.z));
 if(left[0]){const q=left[0];showUnfinished=true;updateWorkHints();navigate(s.stage===4?q.x+(q.i<8?.95:-.95):q.x,s.stage===4?q.z:q.z);toast('Heading to unfinished work. Hold Work when you arrive.');}
};
function taskTitle(){return s.stage===3?['Lift the old floor.','Nothing left behind.','Lay it piece by piece.'][s.floorPhase]:s.stage===4?['Strip the tired walls.','Make good the plaster.','A fresh coat, by hand.'][s.wallPhase]:s.stage===5&&s.machineDirt.some(a=>a.some(Boolean))?'A little care for every machine.':titles[s.stage];}
function taskDescription(){return s.stage===3?['Hold Work near each tile to pry it loose. Lifted pieces stay on the floor until collected.','Press E near loose flooring to collect it. Carry up to 12 pieces to the disposal bin by the front left corner, then E to empty it.','Choose a finish in the journal. Hold Work over each bare section to install the new floor.'][s.floorPhase]:s.stage===4?['Walk along both side walls. Hold Work to strip each wallpaper section.','Hold Work close to each stripped wall section to fill and sand its damaged plaster.','Choose a color, then hold Work beside every prepared wall section to paint it.'][s.wallPhase]:s.stage===5&&s.machineDirt.some(a=>a.some(Boolean))?'Visit all three machines in storage. Press E for a close-up and rub away the dirt by hand before opening Star Signal’s service panel.':descriptions[s.stage];}
function toolName(){return s.stage===3?['Pry bar','Debris bag · '+s.load+'/12','Tile setter'][s.floorPhase]:s.stage===4?['Wallpaper scraper','Plaster trowel','Paint roller'][s.wallPhase]:['Hand truck','Broom','Mop','','','Cleaning cloth / service kit','Hand truck','Free exploration'][s.stage];}
const titles=['Make a little room.','A clean sweep.','Under all that grime.','A floor worth dancing on.','A fresh coat.','Follow the signal.','Bring it home.','A little light again.'];
const descriptions=['Walk to a cabinet and press E to load your hand truck. Pull it through the doorway into back storage, then press E to park.','Walk across the main floor while holding Space. Your broom only reaches the debris around you.','Mop the old floor in small sections. Keep the tool over a patch until the grime is lifted.','Choose a finish, then walk the roller over the floor. Hold Space or turn on Work to lay your tiles.','Choose your wall color, then use the paint action to give the room a new coat.','Walk to Star Signal in storage and press E. Reconnect the circuit in its service panel.','Load Star Signal onto your hand truck. Bring it through the doorway and park it on the main floor.','Your first corner is alive. Walk to Star Signal to play, or try new floor, wall, and cabinet colors.'];
const stepNames=['Store three cabinets','Sweep loose debris','Mop the grime','Lift old flooring','Bag debris and empty it at the bin','Lay new flooring','Strip old wallpaper','Patch damaged walls','Paint each wall section','Hand-clean all three machines','Rewire Star Signal','Return Star Signal to the arcade'];
function jobIndex(){return s.stage<3?s.stage:s.stage===3?3+s.floorPhase:s.stage===4?6+s.wallPhase:s.stage===5?(s.machineDirt.flat().some(v=>v>0)?9:10):s.stage===6?11:12;}
function button(t,fn){const b=document.createElement('button');b.textContent=t;b.onclick=fn;return b;}
function swatches(label,key,names,colors){const l=document.createElement('label');l.textContent=label;$('options').append(l);const row=document.createElement('div');row.className='swatches';names.forEach((n,i)=>{const b=button(n,()=>{s[key]=i;refresh();save();});b.style.setProperty('--swatch',colors[i]);b.setAttribute('aria-pressed',String(s[key]===i));row.append(b);});$('options').append(row);}
function refresh(){const stage=s.stage;$('resumeStatus').textContent=stage===7?'Your saved game has its first corner restored. Restart from beginning to experience every renovation job.':'Saved restoration: '+taskTitle()+' Use Restart from beginning for a fresh abandoned arcade.';$('enter').textContent=stage===0&&M.progress(s)===0?'Open the arcade':'Continue restoration';$('title').textContent=taskTitle();$('description').textContent=taskDescription();$('objective').textContent=taskTitle()+' · '+M.percent(s)+'%';$('progress').style.width=M.progress(s)*100+'%';$('count').textContent=stage===0?`${s.cabinets.filter(c=>c.stored).length} / 3 cabinets parked`:stage<6?`${M.percent(s)}% complete`:stage===7?'FIRST CORNER RESTORED':'STEP '+(stage+1)+' OF 7';$('tool').textContent=toolName();$('work').disabled=!M.workKey(s);$('work').textContent=working?'Work ON · click to stop':'Space · Work';$('work').setAttribute('aria-pressed',String(working));$('options').replaceChildren();
if(stage===3&&s.floorPhase===2||stage===7)swatches('FLOOR','palette',['Midnight','Candy','Seaside','Parquet'],palette.map(p=>p[0]));if(stage===4&&s.wallPhase===2||stage===7){swatches('WALLS','wall',['Teal','Rose','Cream','Ink'],wallColors);}if(stage>=5)swatches('STAR SIGNAL','color',['Mint','Rose','Honey','Lilac'],cabColors);
if(stage===3&&s.floorPhase===1)$('options').append(button('Walk to disposal bin',()=>navigate(-6,6.5,'park')));
$('steps').replaceChildren();stepNames.forEach((n,i)=>{const li=document.createElement('li');li.textContent=(i<jobIndex()?'✓ ':`${i+1}. `)+n;li.className=i<jobIndex()?'done':'';$('steps').append(li);});
floorBatches.forEach((batch,b)=>batch.material=art.floorMaterial(b<2?(b===0?'#aba18b':'#929282'):palette[s.palette][b-2],b<2?'old':s.palette===3?'parquet':s.palette===0?'terrazzo':'tile'));
for(let i=0;i<M.COUNT;i++){const floorPosition=M.tile(i),batchIndex=s.floor[i]>=1?2+(i%17+Math.floor(i/17))%2:(i%3?0:1);tmp.position.set(floorPosition.x,.035,floorPosition.z);tmp.rotation.set(0,0,0);floorBatches.forEach((batch,b)=>{tmp.scale.setScalar(b===batchIndex&&(s.removed[i]<1||s.floor[i]>=1)?1:0);tmp.updateMatrix();batch.setMatrixAt(i,tmp.matrix);});const t=M.tile(i);tmp.position.set(t.x+Math.sin(i*17)*.17,.071,t.z+Math.cos(i*13)*.14);tmp.rotation.set(-Math.PI/2,0,i);tmp.scale.setScalar((s.grime[i]>0?Math.max(.3,s.grime[i]):0)*(.52+(i*71%19)*.045));tmp.updateMatrix();grime.setMatrixAt(i,tmp.matrix);for(let j=0;j<4;j++){tmp.position.set(t.x+((i*7+j*13)%9-4)*.075,.11,t.z+((i*11+j*7)%11-5)*.07);tmp.rotation.set(0,i+j,0);tmp.scale.setScalar(s.dust[i]>0?Math.max(.35,s.dust[i]):0);tmp.updateMatrix();dust.setMatrixAt(i*4+j,tmp.matrix);}}grime.instanceMatrix.needsUpdate=true;dust.instanceMatrix.needsUpdate=true;floorBatches.forEach(b=>b.instanceMatrix.needsUpdate=true);
wallPanel.material=mat(stage>=5?wallColors[s.wall]:'#45616a');partitionMat.color.set(stage>=5?wallColors[s.wall]:'#557078');wallMats.forEach(m=>m.color.set(stage>=5?wallColors[s.wall]:'#59606a'));wallSections.forEach((o,i)=>{o.material=s.wallStrip[i]<1?wallpaperMaterial:mat(s.wallPaint[i]>=1?wallColors[s.wall]:s.wallPatch[i]>=1?'#dfd4ba':'#958c7d');o.scale.y=2.25;wallScars[i].visible=s.wallPatch[i]<1;wallScars[i].material.opacity=1-s.wallPatch[i];});for(let i=0;i<M.COUNT;i++){const q=M.tile(i);tmp.position.set(q.x,.12,q.z);tmp.rotation.set(.08,i*.7,.04);tmp.scale.setScalar(s.loose[i]?1:0);tmp.updateMatrix();rubble.setMatrixAt(i,tmp.matrix);}rubble.instanceMatrix.needsUpdate=true;binFill.scale.y=.15+s.load/12*.45;cabinetBodies[0].color.set(cabColors[s.color]);art.refresh(s);machineStains.forEach((stains,i)=>stains.forEach(stain=>stain.material.opacity=s.machineDirt[i].reduce((a,v)=>a+v,0)/24*.85));toolKit.select(s);updateWorkHints();if(!canSave)$('save').textContent='Session only · storage unavailable';}
function stop(){mouseLook.release();keys.clear();working=false;path=[];autoAction=null;s.player.vx=s.player.vz=0;orbit=false;pointerDown=null;mini.left=mini.right=false;refresh();}
function changed(){if(lastPhase!==phase()){working=false;path=[];autoAction=null;keys.clear();lastPhase=phase();toast(taskDescription());}if(lastStage!==s.stage){working=false;path=[];autoAction=null;keys.clear();toast(['','Space to breathe. Broom unlocked.','Found a brass token. Keep it for the first game.','The old floor is clean. Time to lift it.','New flooring down. Strip the side walls next.','Visit all three machines for hand cleaning.','It lives! Bring Star Signal back to the room.','The first light is on. Welcome back.'][s.stage]);tone(400+s.stage*80);lastStage=s.stage;}refresh();save();}
function interact(){path=[];autoAction=null;const result=M.interact(s);if(result==='clean'){openClean(M.nearest(s));}else if(['collected','unloaded','disposed','full','empty'].includes(result)){toast({collected:'Collected. Bag: '+s.load+' / 12',unloaded:'Debris emptied. Back for the next load.',disposed:'All old flooring disposed. Ready to install.',full:'Bag full. Take it to the disposal bin.',empty:'Your debris bag is empty.'}[result]);}else if(result==='repair'){stop();renderWires();$('repair').showModal();}else if(result==='play')openGame();else if(result==='loaded')toast(s.stage===6?'Loaded. Bring Star Signal onto the main floor; E parks it.':'Hand truck loaded. Walk to storage; E parks the cabinet.');else if(result==='stored')toast('Parked safely in storage.');else if(result==='nearer')toast(s.stage===3?'Walk closer to loose flooring or the disposal bin.':'Walk closer to a cabinet first.');else if(result==='unavailable')toast('This cabinet is waiting for a later restoration.');else if(result==='dropped')toast('Cabinet set down. E loads it again.');changed();}
function navigate(x,z,action=null){document.getElementById("world").focus();path=M.path(s,x,z);autoAction=action;if(path.length){targetRing.position.set(path.at(-1).x,.1,path.at(-1).z);targetRing.visible=true;}else{autoAction=null;if(Math.hypot(s.player.x-x,s.player.z-z)>.7)toast('That spot is blocked. Try an open patch of floor.');}}
const mouseLook=createMouseLook({element:renderer.domElement,canLock:()=>follow&&!modal()&&$('journal').hidden&&!document.hidden,onLook:(x,y)=>{yaw-=x*.0025;pitch=THREE.MathUtils.clamp(pitch+y*.002,-.12,.6);},onRelease:()=>{keys.clear();working=false;path=[];autoAction=null;orbit=false;pointerDown=null;s.player.vx=s.player.vz=0;refresh();},onChange:locked=>{$('reticle').hidden=!locked;$('mouseLock').textContent=locked?'Esc · Release mouse':'Mouse look';$('mouseLock').setAttribute('aria-pressed',String(locked));},onError:()=>{$('mouseLock').title='Free mouse look: move to look, hold near either side to keep turning. Escape releases the mouse.';toast('Free mouse look enabled · no dragging needed · screen edges keep turning · Esc releases');}});
$('mouseLock').onclick=()=>{if(mouseLook.active())mouseLook.release();else{if(!$('journal').hidden)$('journalToggle').click();mouseLook.request();}};
new MutationObserver(()=>{if(modal()||!$('journal').hidden)mouseLook.release();}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['open','hidden']});
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0&&e.button!==2)return;$('world').focus();if(mouseLook.active()){if(e.button===0&&M.workKey(s)){working=true;refresh();}return;}if(follow&&e.pointerType==='mouse'&&e.button===0){if(!$('journal').hidden)$('journalToggle').click();mouseLook.request();return;}pointerDown={x:e.clientX,y:e.clientY,button:e.button};orbit=e.button===2;renderer.domElement.setPointerCapture(e.pointerId);});
renderer.domElement.addEventListener('pointermove',e=>{if(orbit&&!mouseLook.active()){yaw-=e.movementX*.006;pitch=THREE.MathUtils.clamp(pitch+e.movementY*.004,follow?-.12:.35,follow?.6:1.25);}});
renderer.domElement.addEventListener('pointerup',e=>{if(mouseLook.active()){if(e.button===0){working=false;refresh();}return;}if(follow&&e.pointerType==='mouse'&&e.button===0)return;const start=pointerDown;orbit=false;pointerDown=null;if(!start||start.button!==0||Math.hypot(start.x-e.clientX,start.y-e.clientY)>12)return;keys.clear();pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(cabinetGroups,true);if(hits.length&&s.held<0){let o=hits[0].object;while(o&&o.userData.cabinet===undefined)o=o.parent;const i=o?.userData.cabinet;if(i!==undefined){const c=s.cabinets[i];if(M.nearest(s)===i){interact();return;}navigate(c.x,c.z+1.75,i);return;}}
if(raycaster.ray.intersectPlane(ground,hit))navigate(hit.x,hit.z,s.held>=0&&(hit.z< -6.3||s.stage===6&&hit.z> -3.5)?'park':null);});
document.addEventListener('pointerup',e=>{if(e.button===0&&working&&mouseLook.active()&&!e.target.closest('button')){working=false;refresh();}});
renderer.domElement.addEventListener('pointercancel',()=>{orbit=false;pointerDown=null;working=false;refresh();});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance+e.deltaY*(follow?.003:.012),follow?2:9,follow?5:34);},{passive:false});
function modal(){return !!document.querySelector('dialog[open]');}
window.addEventListener('keydown',e=>{if(modal()||((e.key===' '||e.key==='Enter')&&e.target.closest('button,summary')))return;const k=e.key.toLowerCase();if(!$('journal').hidden&&!['j','c','escape'].includes(k))return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','e','q','r','j','c','escape'].includes(k)){e.preventDefault();if(k==='j'&&!e.repeat)$('journalToggle').click();else if(k==='c'&&!e.repeat)$('camera').click();else if(k==='e'&&!e.repeat)interact();else if(k==='escape'){stop();if(!$('journal').hidden)$('journalToggle').click();refresh();}else{keys.add(k);if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){path=[];autoAction=null;}}}});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{stop();if(mini.running){mini.running=false;$('score').textContent='Paused. Press Play for a new round.';}refresh();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();mini.running=false;save();refresh();}});
$('interact').onclick=interact;$('work').onclick=()=>{working=!working;refresh();$('world').focus();};$('camera').onclick=()=>{stop();follow=!follow;distance=follow?4.2:28;pitch=follow?.24:.73;$('camera').textContent=follow?'Room camera':'Chase camera';};$('home').onclick=()=>{yaw=follow?0:.52;pitch=follow?.24:.73;distance=follow?4.2:28;};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'Sound off':'Sound on';$('sound').setAttribute('aria-pressed',String(!muted));tone();};$('journalToggle').onclick=()=>{stop();$('journal').hidden=!$('journal').hidden;$('journalToggle').textContent=$('journal').hidden?'Show journal':'Hide journal';$('objective').hidden=!$('journal').hidden;};$('help').onclick=()=>{stop();$('welcome').showModal();};$('enter').onclick=()=>{$('welcome').close();$('world').focus();toast(taskDescription());if(matchMedia('(pointer:fine)').matches)mouseLook.request();};function showRestart(){stop();if(!$('welcome').open)$('welcome').showModal();$('confirm').hidden=false;$('confirm').scrollIntoView({block:'nearest'});$('yes').focus();}
$('restart').onclick=showRestart;$('new').onclick=showRestart;$('no').onclick=()=>$('confirm').hidden=true;$('yes').onclick=()=>{s=M.fresh();lastStage=0;stop();yaw=0;pitch=.24;distance=4.2;cameraBoom=4.2;follow=true;$('camera').textContent='Room camera';$('journal').hidden=false;$('journalToggle').textContent='Hide journal';$('objective').hidden=true;$('confirm').hidden=true;changed();$('welcome').close();$('world').focus();};
document.querySelectorAll('[data-dir]').forEach(b=>{const k={up:'w',down:'s',left:'a',right:'d'}[b.dataset.dir];b.onpointerdown=e=>{e.preventDefault();path=[];autoAction=null;keys.add(k);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(k);});
function renderWires(){const row=$('wires');row.replaceChildren();s.wires.forEach((rot,i)=>{const b=button('',()=>{s.wires[i]=(rot+1)%4;renderWires();row.children[i].focus();save();tone(300);});b.setAttribute('aria-label',`Connector ${i+1}, rotation ${rot*90} degrees. Rotate clockwise`);b.innerHTML=`<svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="32" fill="#263d4d"/><path d="M50 0 V50 H100" fill="none" stroke="#a1e5c7" stroke-width="10" transform="rotate(${rot*90} 50 50)"/><circle cx="50" cy="50" r="7" fill="#ddc8a1"/></svg>`;row.append(b);});}
$('closeRepair').onclick=()=>$('repair').close();$('hint').onclick=()=>$('wireStatus').textContent='Input → down → right → up → right → down → output.';$('test').onclick=()=>{if(M.repair(s)){$('repair').close();changed();}else{$('wireStatus').textContent='No signal. Both ends of each connector must join the path. Try the hint.';tone(130);}};

let cleaningCabinet=0,clothDown=false,cleanRenderer=null,cleanBase=null;
function cabinetCloseup(){try{cleanRenderer??=new THREE.WebGLRenderer({antialias:true,alpha:true});cleanRenderer.setSize(480,360);cleanRenderer.setClearColor('#172932',0);cleanRenderer.outputColorSpace=THREE.SRGBColorSpace;cleanRenderer.toneMapping=THREE.ACESFilmicToneMapping;const view=new THREE.Scene();view.add(new THREE.HemisphereLight('#d5e6df','#433727',2));const light=new THREE.DirectionalLight('#ffe6bd',3);light.position.set(-2,4,4);view.add(light);const model=cabinetGroups[cleaningCabinet].clone(true);model.position.set(0,0,0);model.rotation.set(0,0,0);model.traverse(o=>{if(o.userData.cleanStain)o.visible=false;});view.add(model);const lens=new THREE.PerspectiveCamera(46,480/360,.05,20);lens.position.set(.06,1.38,2.15);lens.lookAt(0,1.4,.3);cleanRenderer.render(view,lens);cleanBase=document.createElement('canvas');cleanBase.width=480;cleanBase.height=360;cleanBase.getContext('2d').drawImage(cleanRenderer.domElement,0,0);}catch{cleanBase=null;}}

const cloth=$('cloth'),cg=cloth.getContext('2d');
function drawClean(){cg.fillStyle='#162832';cg.fillRect(0,0,480,360);cg.fillStyle=cabColors[cleaningCabinet===0?s.color:cleaningCabinet===1?2:3];cg.fillRect(40,15,400,335);cg.fillStyle='#e6d4ac';cg.font='bold 22px monospace';cg.textAlign='center';cg.fillText(['STAR SIGNAL','MOON RALLY','PIXEL GARDEN'][cleaningCabinet],240,48);cg.fillStyle='#0b1924';cg.fillRect(70,65,340,166);cg.strokeStyle='#93c9bb';cg.lineWidth=3;cg.strokeRect(88,81,304,130);cg.fillStyle='#456b6f';cg.fillRect(62,243,356,52);cg.fillStyle='#dcb09d';for(let i=0;i<3;i++){cg.beginPath();cg.arc(280+i*38,267,11,0,7);cg.fill();}cg.fillStyle='#d9c397';cg.beginPath();cg.arc(140,262,15,0,7);cg.fill();cg.fillStyle='#28343a';cg.fillRect(200,307,80,35);if(cleanBase){cg.fillStyle='#182b32';cg.fillRect(0,0,480,360);cg.drawImage(cleanBase,0,0);}s.machineDirt[cleaningCabinet].forEach((v,i)=>{if(!v)return;const x=(i%6)*80,y=Math.floor(i/6)*90;cg.save();cg.beginPath();cg.rect(x,y,80,90);cg.clip();cg.fillStyle='rgba(107,93,66,'+(v*.22)+')';cg.fillRect(x,y,80,90);cg.globalAlpha=Math.max(.3,v)*.9;cg.drawImage(art.dirtMap.image,x-25,y-30,140,160);cg.globalAlpha=Math.max(.3,v)*.4;cg.drawImage(art.dirtMap.image,x+10,y+15,85,90);cg.restore();if(s.machineDirt[cleaningCabinet].filter(Boolean).length<=4){cg.strokeStyle='#f3bf61';cg.lineWidth=2;cg.strokeRect(x+3,y+3,74,84);}});const dirty=s.machineDirt[cleaningCabinet].filter(Boolean).length;Array.from($('patches').children).forEach((b,i)=>{b.disabled=!s.machineDirt[cleaningCabinet][i];b.textContent='Patch '+(i+1)+(b.disabled?' · clean':' · needs cleaning');});$('cleanStatus').textContent=(dirty?Math.min(99,Math.floor((1-s.machineDirt[cleaningCabinet].reduce((a,v)=>a+v,0)/24)*100)):100)+'% clean · '+(s.machineDirt[cleaningCabinet].some(Boolean)?dirty+(dirty===1?' patch':' patches')+' left · Rub the dirt; final patches are outlined.':'Clean and ready.');}
function openClean(i){stop();cleaningCabinet=i;cabinetCloseup();$('cleanTitle').textContent=['Star Signal','Moon Rally','Pixel Garden'][i]+' · hand cleaning';$('patches').replaceChildren();for(let p=0;p<24;p++){$('patches').append(button('Patch '+(p+1),()=>{M.wipe(s,i,p);drawClean();changed();}));}drawClean();$('clean').showModal();}
function rub(e){if(!clothDown)return;const r=cloth.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*480,y=(e.clientY-r.top)/r.height*360;for(let i=0;i<24;i++){const px=(i%6)*80+40,py=Math.floor(i/6)*90+45;if(Math.hypot(px-x,py-y)<67)M.wipe(s,cleaningCabinet,i);}drawClean();refresh();save();}
cloth.onpointerdown=e=>{clothDown=true;cloth.setPointerCapture(e.pointerId);rub(e);};cloth.onpointermove=rub;cloth.onpointerup=cloth.onpointercancel=()=>clothDown=false;$('closeClean').onclick=()=>{$('clean').close();clothDown=false;changed();};$('clean').addEventListener('close',()=>clothDown=false);

const mini={running:false,x:270,time:0,score:0,stars:[],spawn:0,left:false,right:false},screen=$('screen'),g=screen.getContext('2d');
function openGame(){stop();mini.running=false;$('score').textContent=`Best: ${s.best} stars. Ready when you are.`;$('game').showModal();screen.focus();}
$('closeGame').onclick=()=>{$('game').close();mini.running=false;};$('game').addEventListener('close',()=>{mini.running=false;mini.left=mini.right=false;});$('start').onclick=()=>{Object.assign(mini,{running:true,x:270,time:30,score:0,stars:[],spawn:0,left:false,right:false});screen.focus();};screen.onpointermove=e=>{const r=screen.getBoundingClientRect();mini.x=THREE.MathUtils.clamp((e.clientX-r.left)/r.width*540,25,515);mini.left=mini.right=false;};screen.onpointerdown=screen.onpointermove;screen.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();mini[e.key==='ArrowLeft'?'left':'right']=true;}};screen.onkeyup=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight')mini[e.key==='ArrowLeft'?'left':'right']=false;};screen.onblur=()=>{mini.left=mini.right=false;};
function miniFrame(dt){if(!$('game').open)return;const nebula=g.createRadialGradient(360,90,10,270,170,380);nebula.addColorStop(0,'#254258');nebula.addColorStop(.5,'#10273d');nebula.addColorStop(1,'#07111d');g.fillStyle=nebula;g.fillRect(0,0,540,340);g.strokeStyle='#75b7ac20';g.lineWidth=1;for(let i=0;i<6;i++){g.beginPath();g.moveTo(50+i*82,340);g.lineTo(235+i*14,195);g.stroke();}for(let i=0;i<5;i++){g.beginPath();g.moveTo(0,235+i*24);g.lineTo(540,235+i*24);g.stroke();}for(let i=0;i<35;i++){g.fillStyle='#9ab3c477';g.fillRect(i*83%540,i*53%300,2,2);}if(mini.running){mini.time-=dt;mini.spawn-=dt;mini.x=THREE.MathUtils.clamp(mini.x+((mini.right?1:0)-(mini.left?1:0))*360*dt,25,515);if(mini.spawn<=0){mini.stars.push({x:30+Math.random()*480,y:-10});mini.spawn=.6;}for(const star of mini.stars){star.y+=125*dt;if(star.y>295&&star.y<320&&Math.abs(star.x-mini.x)<33){mini.score++;star.y=400;tone(700);}}mini.stars=mini.stars.filter(star=>star.y<350);$('score').textContent=`${mini.score} / 12 stars · ${Math.max(0,Math.ceil(mini.time))} seconds`;if(mini.time<=0){mini.running=false;s.best=Math.max(s.best,mini.score);save();$('score').textContent=`${mini.score>=12?'Constellation lit!':'Try again!'} ${mini.score} stars · Best ${s.best}`;}}
g.fillStyle='#eddbab';g.font='24px system-ui';g.textAlign='center';for(const star of mini.stars)g.fillText('✦',star.x,star.y);g.fillStyle='#9edfc3';g.shadowColor='#74e6c1';g.shadowBlur=14;g.beginPath();g.roundRect(mini.x-30,310,60,10,4);g.fill();g.shadowBlur=0;g.fillStyle='#e4b695';g.beginPath();g.moveTo(mini.x-8,309);g.lineTo(mini.x,300);g.lineTo(mini.x+8,309);g.fill();if(!mini.running){g.font='bold 27px monospace';g.fillStyle='#e1d4ae';g.fillText('STAR SIGNAL',270,150);g.font='10px monospace';g.fillStyle='#8ebcae';g.fillText('A SIGNAL FROM ANOTHER WORLD',270,175);}g.fillStyle='#030b1620';for(let y=0;y<340;y+=3)g.fillRect(0,y,540,1);const vignette=g.createRadialGradient(270,170,110,270,170,320);vignette.addColorStop(0,'transparent');vignette.addColorStop(1,'#00000070');g.fillStyle=vignette;g.fillRect(0,0,540,340);}
const markerButtons=[];
function updateMarkers(){
  const items=[];
  if(s.held>=0){const b=M.bays[s.held];items.push({name:s.stage===6?'Place on restored floor':'Park in storage',x:s.stage===6?0:b.x,z:s.stage===6?2:-7.8,y:.4,fn:()=>navigate(s.stage===6?0:b.x,s.stage===6?2:-7.8,'park')});}
  else if(s.stage===3&&s.floorPhase===1){items.push({name:'Empty debris bag · '+s.load+'/12',x:-7,z:7.2,y:1.1,fn:()=>navigate(-6,6.5,'park')});}else if(s.stage===0||s.stage>=5){s.cabinets.forEach((c,i)=>{if((s.stage===0&&!c.stored)||(s.stage===5&&(s.machineDirt[i].some(Boolean)||i===0))||(s.stage>5&&i===0))items.push({name:['Star Signal','Moon Rally','Pixel Garden'][i],x:c.x,z:c.z,y:2.8,fn:()=>{if(M.nearest(s)===i)interact();else navigate(c.x,c.z+1.75,i);}});});}
  while(markerButtons.length<items.length){const b=button('',()=>{});$('markers').append(b);markerButtons.push(b);}
  markerButtons.forEach((b,i)=>{const item=items[i];b.hidden=!item;if(!item)return;const p=new THREE.Vector3(item.x,item.y,item.z).project(camera);b.hidden=p.z>1||p.z< -1||Math.abs(p.x)>1||Math.abs(p.y)>1;b.textContent=item.name;b.onclick=item.fn;b.style.left=(p.x*.5+.5)*innerWidth+'px';b.style.top=(-p.y*.5+.5)*innerHeight+'px';});
}
let statFrames=0,statTime=performance.now();
let stalled=0;
function frame(now){const dt=Math.min((now-last)/1000,.04);last=now;mouseLook.update(dt);if(!document.hidden&&!modal()){
if(keys.has('q'))yaw+=dt;if(keys.has('r'))yaw-=dt;let dx=0,dz=0;const right=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),forward=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0);
if(right||forward){dx=Math.cos(yaw)*right-Math.sin(yaw)*forward;dz=-Math.sin(yaw)*right-Math.cos(yaw)*forward;}else if(path.length){while(path.length&&Math.hypot(path[0].x-s.player.x,path[0].z-s.player.z)<.19)path.shift();if(path.length){dx=path[0].x-s.player.x;dz=path[0].z-s.player.z;}else{s.player.vx=s.player.vz=0;if(autoAction!==null){const action=autoAction;autoAction=null;if(action==='park'||M.nearest(s)===action)interact();}}}
const ox=s.player.x,oz=s.player.z;M.step(s,dx,dz,dt);if(follow)s.player.yaw=yaw+Math.PI;if(path.length&&Math.hypot(s.player.x-ox,s.player.z-oz)<.001){stalled+=dt;if(stalled>1){path=[];autoAction=null;stalled=0;toast('A tight spot. Try backing up or setting the cabinet down.');}}else stalled=0;
if((working||keys.has(' '))&&M.workKey(s)){workClock+=dt;if(workClock>.12){workClock=0;const before=phase(),n=M.work(s);if(n||phase()!==before){changed();tone(s.stage===1?180:300);}}}if(now-lastSave>2000){save();lastSave=now;}}
walkPhase+=Math.hypot(s.player.vx||0,s.player.vz||0)*dt*2.5;avatar.position.set(s.player.x,0,s.player.z);avatar.rotation.y=s.player.yaw;const kneel=character.animate({dt,shortTool:s.stage===3&&s.floorPhase===2,speed:Math.hypot(s.player.vx||0,s.player.vz||0),phase:walkPhase,time:now,working:working||keys.has(' '),hauling:s.held>=0,tool:!!M.workKey(s),wall:s.stage===4,side:s.player.x<0?-1:1});debrisBag.visible=s.stage===3&&s.floorPhase===1&&s.load>0;tool.visible=!!M.workKey(s);tool.rotation.y=(working||keys.has(' '))?Math.sin(now*.012)*.22:0;if(s.stage===4){const side=s.player.x<0?-1:1;tool.position.set(Math.cos(s.player.yaw)*side*.7,1.15+((working||keys.has(' '))?Math.sin(now*.012)*.12:0),Math.sin(s.player.yaw)*side*.7);tool.rotation.y=side*Math.PI/2-s.player.yaw;}else tool.position.set(.33,s.stage===3&&s.floorPhase===2?.78-kneel*.62:.06,s.stage===3&&s.floorPhase===2?.24+kneel*.38:.62);
s.cabinets.forEach((c,i)=>{cabinetGroups[i].position.set(c.x,s.held===i?.13:0,c.z);cabinetGroups[i].rotation.y=c.yaw;});dolly.visible=s.held>=0;if(dolly.visible){const c=s.cabinets[s.held];dolly.position.set(c.x,0,c.z);dolly.rotation.y=c.yaw;}
glow.intensity=s.repaired?8:0;glow.position.set(s.cabinets[0].x,1.7,s.cabinets[0].z+.8);targetRing.visible=path.length>0;targetRing.rotation.z=now*.001;
if(follow){const cp=M.cameraPosition(s,yaw,distance,pitch),allowed=Math.hypot(cp.x-s.player.x,cp.z-s.player.z);cameraBoom=Math.min(allowed,THREE.MathUtils.lerp(cameraBoom,allowed,1-Math.exp(-5*dt)));const ratio=allowed?cameraBoom/allowed:0;cp.x=s.player.x+(cp.x-s.player.x)*ratio;cp.z=s.player.z+(cp.z-s.player.z)*ratio;cp.y=1.65+(cp.y-1.65)*ratio;avatar.visible=Math.hypot(cp.x-s.player.x,cp.z-s.player.z)>1.8;camera.position.set(cp.x,cp.y,cp.z);camera.lookAt(s.player.x-Math.sin(yaw)*3,1.25-Math.sin(pitch)*2,s.player.z-Math.cos(yaw)*3);wallMats.forEach(m=>m.opacity=1);partitionMat.opacity=1;}else{avatar.visible=true;const desired=new THREE.Vector3(0,.6,-1);target.lerp(desired,1-Math.exp(-4*dt));camera.position.set(target.x+Math.sin(yaw)*Math.cos(pitch)*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(target);wallMats[0].opacity=camera.position.x<0?.12:.9;wallMats[1].opacity=camera.position.x>0?.12:.9;partitionMat.opacity=.22;}

const near=M.nearest(s);$('interact').textContent=s.stage===3&&s.floorPhase===1?'E · Collect / empty':s.held>=0?'E · Park cabinet':near>=0?(s.stage===5?'E · Clean / repair':s.stage===7&&near===0?'E · Play':'E · Load cabinet'):'E · Interact';$('context').textContent=mouseLook.active()?'Mouse to look · WASD to move · E interact · hold click / Space to work · J journal · Esc cursor':follow?'Click the scene for mouse look · WASD to move · J journal · C room view':s.held>=0?'Pull the cabinet through the wide doorway · E to park':path.length?'Walking… WASD takes control':M.workKey(s)?'Hold Work on one section · right-drag to look · journal for details':near>=0?'E to interact · right-drag to look around':'WASD to walk · click floor to walk · right-drag to orbit';if(now>toastUntil)$('toast').style.opacity=0;
updateMarkers();art.animate(now);miniFrame(dt);renderer.render(scene,camera);statFrames++;if(now-statTime>1500){$('renderStats').textContent=`${Math.round(statFrames*1000/(now-statTime))} FPS · ${renderer.info.render.calls} draw calls · ${Math.round(renderer.info.render.triangles/1000)}k triangles · ${renderer.getPixelRatio().toFixed(2)}× resolution`;statFrames=0;statTime=now;}requestAnimationFrame(frame);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});window.addEventListener('pagehide',save);refresh();$('welcome').showModal();$('enter').focus();requestAnimationFrame(frame);
