const assert=require('node:assert/strict');
const M=require('../prototypes/arcade3d/model.js');
let s=M.fresh(),seconds=0;
function walkTo(x,z,work=false){let route=M.path(s,x,z);assert(route.length||Math.hypot(s.player.x-x,s.player.z-z)<.5,'reachable target');let frames=0;while(route.length&&frames++<6000){while(route.length&&Math.hypot(route[0].x-s.player.x,route[0].z-s.player.z)<.19)route.shift();if(!route.length)break;M.step(s,route[0].x-s.player.x,route[0].z-s.player.z,1/60);if(work)M.work(s);seconds+=1/60;if(frames%97===0){s=JSON.parse(JSON.stringify(s));assert(M.valid(s));}}s.player.vx=s.player.vz=0;assert(frames<6000,`route stalled to ${x},${z} at ${s.player.x},${s.player.z}`);}
assert(M.valid(s));assert(M.blocked(s,5,-5));assert(!M.blocked(s,0,-5));
for(let i=0;i<3;i++){walkTo(s.cabinets[i].x,s.cabinets[i].z+1.75);assert.equal(M.nearest(s),i);assert.equal(M.interact(s),'loaded');walkTo(M.bays[i].x,-7.8);assert.equal(M.interact(s),'stored');assert(!M.blocked(s,s.player.x,s.player.z),'parking leaves player free');}
assert.equal(s.stage,1);console.log('PASS three complete cabinet routes through storage doorway');
function finishSurface(){const initial=s.stage,phase=s.floorPhase,wall=s.wallPhase;for(let i=0;i<M.COUNT&&s.stage===initial&&s.floorPhase===phase&&s.wallPhase===wall;i++){const q=M.tile(i);walkTo(q.x,q.z);for(let j=0;j<12&&s.stage===initial&&s.floorPhase===phase&&s.wallPhase===wall;j++)M.work(s);}}
finishSurface();assert.equal(s.stage,2);finishSurface();assert.equal(s.stage,3);assert.equal(s.floorPhase,0);finishSurface();assert.equal(s.floorPhase,1);assert.equal(s.loose.reduce((a,v)=>a+v,0),M.COUNT);
let trips=0;while(s.floorPhase===1&&trips++<30){for(let i=0;i<M.COUNT&&s.load<12;i++){if(s.loose[i]){const q=M.tile(i);walkTo(q.x,q.z);M.interact(s);}}assert(s.load>0,'debris collected');walkTo(-6,6.5);assert(['unloaded','disposed'].includes(M.interact(s)));assert.equal(s.load,0);}
assert.equal(s.floorPhase,2);assert(trips>=13,'capacity requires disposal trips');finishSurface();assert.equal(s.stage,4);
for(let phase=0;phase<3;phase++){assert.equal(s.wallPhase,phase);for(let i=0;i<16&&s.stage===4&&s.wallPhase===phase;i++){const q=M.wallTile(i);walkTo(q.x+(i<8?.9:-.9),q.z);for(let j=0;j<13&&s.stage===4&&s.wallPhase===phase;j++)M.work(s);}}assert.equal(s.stage,5);
assert(!M.repair(s),'dirty machines gate repairs');for(let i=0;i<3;i++){walkTo(s.cabinets[i].x,s.cabinets[i].z+1.75);assert.equal(M.interact(s),'clean');for(let patch=0;patch<24;patch++)for(let rub=0;rub<3;rub++)M.wipe(s,i,patch);}
walkTo(s.cabinets[0].x,s.cabinets[0].z+1.75);assert.equal(M.interact(s),'repair');assert.equal(M.repair(s),false);s.wires=[...M.solution];assert(M.repair(s));assert.equal(M.interact(s),'loaded');walkTo(0,1);assert.equal(M.interact(s),'restored');assert.equal(s.stage,7);assert.equal(M.interact(s),'play');assert(M.valid(JSON.parse(JSON.stringify(s))));console.log('PASS complete expanded restoration, '+trips+' debris trips, all wall passes, three machine cleanings and cabinet return ('+seconds.toFixed(1)+' simulated seconds)');
for(const pos of [{x:8.2,z:4},{x:-8.2,z:4},{x:0,z:-5},{x:2,z:-4},{x:0,z:-10}]){const c=M.fresh();Object.assign(c.player,pos);for(let j=0;j<32;j++){const eye=M.cameraPosition(c,j*Math.PI/16);assert(!M.cameraBlocked(c,eye.x,eye.z,eye.y),'camera avoids walls');}}
const legacy=JSON.parse(JSON.stringify(s));legacy.version=2;for(const k of ['removed','loose','load','floorPhase','wallPhase','wallStrip','wallPatch','wallPaint','machineDirt'])delete legacy[k];assert(M.valid(M.migrate(legacy)));assert.equal(M.migrate(legacy).stage,7);assert.equal(M.migrate({...legacy,stage:1}).floorPhase,0);assert.equal(M.migrate(null),null);
const centered=M.fresh();centered.cabinets=[];centered.player.x=0;centered.player.z=0;
for(let i=0;i<64;i++){const yaw=i*Math.PI/32,eye=M.cameraPosition(centered,yaw),dx=eye.x-centered.player.x,dz=eye.z-centered.player.z;assert(Math.abs(dx*Math.cos(yaw)-dz*Math.sin(yaw))<1e-9,'camera has no shoulder offset at any heading');assert(dx*Math.sin(yaw)+dz*Math.cos(yaw)>=0,'camera stays behind');}
centered.player.z=6;assert.equal(M.cameraPosition(centered,0).z,10.2,'open front curb does not compress the camera');
const obstacle=M.fresh();obstacle.player.x=5;obstacle.player.z=-3.5;for(let i=0;i<300;i++)M.step(obstacle,0,-1,1/60);assert(obstacle.player.z>-4.5);assert(!M.blocked(obstacle,obstacle.player.x,obstacle.player.z));
const bound=M.fresh();for(let i=0;i<3000;i++)M.step(bound,1,1,1/60);assert(!M.blocked(bound,bound.player.x,bound.player.z));
const speed=M.fresh();M.step(speed,1,0,1/60);assert(speed.player.vx>0&&speed.player.vx<4.2);for(let i=0;i<90;i++)M.step(speed,0,0,1/60);assert(Math.abs(speed.player.vx)<.001);
for(let i=0;i<6;i++){const bad=M.fresh();bad.stage=5;bad.machineDirt.forEach(a=>a.fill(0));bad.wires=[...M.solution];bad.wires[i]=(bad.wires[i]+1)%4;assert(!M.repair(bad));}
for(const invalid of [null,{}, {...s,stage:99},{...s,held:9},{...s,player:{x:NaN,z:0,yaw:0}},{...s,dust:[]}])assert(!M.valid(invalid));
console.log('PASS wall/boundary collision, acceleration/release, six circuit failures, save validation');
