// DOM-stub integration tests. Browser UI checks are logged separately.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/../prototypes/m1/index.html','utf8');
assert(!/<(?:script|link|img)[^>]+(?:src|href)=/i.test(html),'standalone HTML must not load assets');assert(!/\bfetch\s*\(/.test(html));
function boot({width=960,storageThrows=false,fixture=false}={}){let now=0,frame,focus,els=new Map(),winEvents={},docEvents={},writes=0;const noop=()=>{};const ctx=new Proxy({},{get:()=>noop,set:()=>true});
function el(id){if(!els.has(id))els.set(id,{id,tagName:id==='floor'?'CANVAS':'BUTTON',type:['sensitivity','smoothing'].includes(id)?'range':'checkbox',checked:false,value:1,style:{},textContent:'',innerHTML:'',hidden:false,events:{},addEventListener(name,fn){this.events[name]=fn;},setAttribute:noop,focus(){focus=id;},getContext:()=>ctx,setPointerCapture:noop,getBoundingClientRect:()=>({left:0,top:0,right:width,bottom:width*2/3,width,height:width*2/3}),clientWidth:width,clientHeight:width*2/3});return els.get(id);}
const context=vm.createContext({console,document:{getElementById:el,addEventListener:(k,fn)=>docEvents[k]=fn,hidden:false},window:{addEventListener:(k,fn)=>winEvents[k]=fn},localStorage:{getItem(){if(storageThrows)throw Error('denied');return null;},setItem(){if(storageThrows)throw Error('denied');writes++;},removeItem(){if(storageThrows)throw Error('denied');}},matchMedia:()=>({matches:false}),performance:{now:()=>now},requestAnimationFrame:fn=>frame=fn,navigator:{userAgent:'Chrome/146.0.0.0'},innerWidth:width,innerHeight:800});
vm.runInContext(html.match(/<script id="simulation">([\s\S]*?)<\/script>/)[1]+'\nglobalThis.core=SweepCore;',context);
if(fixture){const create=context.core.create;context.core.create=()=>{const s=create(0);s.pieces=[context.core.body(0,'leaf',870,300),context.core.body(1,'keys',750,65)];s.total=1;return s;};}
let presentation=html.match(/<script id="presentation">([\s\S]*?)<\/script>/)[1];presentation=presentation.replace(/\}\)\(\);\s*$/, 'globalThis.inspect=()=>({s,mode,held,pointer,pressureLatch,liftLatch,acc,input:input()});})();');vm.runInContext(presentation,context);
return{el,context,events:winEvents,docEvents,state:context.inspect,advance(seconds,fps=60){for(let i=0;i<Math.round(seconds*fps);i++){now+=1000/fps;frame(now);}},key(k){winEvents.keydown({key:k,target:{tagName:'CANVAS'},preventDefault:noop,repeat:false});},up(k){winEvents.keyup({key:k});},focus:()=>focus,writes:()=>writes};}
const reports=[];function test(name,fn){fn();reports.push(name);console.log('PASS',name);}
test('Storage blocked: start, pause, resume, long background gap, input clear',()=>{const b=boot({storageThrows:true});b.el('start').onclick();b.key('Shift');b.key('d');b.advance(.2);assert(b.state().s.broom.x>180);b.events.blur();const t=b.state().s.time;assert.equal(b.state().mode,'pause');assert.equal(b.state().held.size,0);b.advance(600,1);assert.equal(b.state().s.time,t);b.el('resume').onclick();b.advance(.1);assert(b.state().s.time-t<.11);assert(b.el('record').textContent.includes('memory only'));});
test('UI complete result and one-action restart clears totals, motion, combos',()=>{const b=boot({fixture:true});b.el('start').onclick();b.advance(.5);assert.equal(b.state().mode,'result');assert(b.el('card').innerHTML.includes('That’s better.'));assert(b.writes()>0);b.el('again').onclick();assert.equal(b.state().s.weight,0);assert.equal(b.state().s.score,0);assert.equal(b.state().s.group,null);assert.equal(b.state().mode,'play');});
test('50 rapid UI restarts, toggles and focus clearing',()=>{const b=boot();b.el('start').onclick();for(let i=0;i<50;i++){b.el('lift').onclick();b.el('pressure').onclick();b.key('r');assert.equal(b.state().liftLatch,false);assert.equal(b.state().pressureLatch,false);assert.equal(b.state().s.time,0);assert(b.state().s.pieces.every(p=>p.vx===0&&p.vy===0));}b.key(' ');b.key('d');b.advance(.2);assert.equal(b.state().s.contacts,0);});
test('Pointer coordinates yield identical physics at 480 / 960 CSS pixels',()=>{const states=[];for(const width of [480,960]){const b=boot({width});b.el('start').onclick();b.el('floor').events.pointermove({clientX:width*.7,clientY:width*.3});b.advance(2);states.push(b.state().s);}assert.equal(JSON.stringify(states[0]),JSON.stringify(states[1]));});
test('Canvas exit and reentry: bounded motion, no stale pressure',()=>{const b=boot();b.el('start').onclick();b.el('floor').events.pointerdown({clientX:400,clientY:300,button:0,pointerId:1});b.advance(.2);b.el('floor').events.pointerleave();const x=b.state().s.broom.x;b.advance(.5);assert.equal(b.state().s.broom.x,x);b.el('floor').events.pointermove({clientX:900,clientY:300});b.advance(1/120,120);assert(Math.abs(b.state().s.broom.x-x)<=500/120+1e-8);b.el('floor').events.pointermove({clientX:1500,clientY:300});assert.equal(b.state().pointer.inside,false);});
test('Keyboard can rotate a grounded stationary broom; reset local works',()=>{const b=boot();b.el('start').onclick();b.key('d');b.advance(.2);b.up('d');b.key('q');b.advance(.3);assert(Math.abs(b.state().s.broom.a)>0);b.el('resetLocal').onclick();assert.equal(b.el('record').textContent,'Personal best: —');});
fs.writeFileSync(__dirname+'/../artifacts/lifecycle-results.json',JSON.stringify(reports,null,2));

module.exports={boot};
