/* After Hours: deterministic restoration state, followed by the browser presentation. */
const Arcade = (()=>{
 const solution=[2,1,2,0,3,0], colors=['#72b5ac','#ca8195','#daa85e','#8292c5'];
 function fresh(){return {version:1,stage:0,cabinets:[{x:230,y:370,stored:false},{x:420,y:420,stored:false},{x:650,y:360,stored:false}],dust:Array(153).fill(1),grime:Array(153).fill(1),floor:Array(153).fill(0),palette:0,wall:0,cabinet:0,wires:[0,2,3,2,0,1],repaired:false,returned:false,best:0};}
 function valid(s){return s&&s.version===1&&Number.isInteger(s.stage)&&s.stage>=0&&s.stage<=7&&['dust','grime','floor'].every(k=>Array.isArray(s[k])&&s[k].length===153&&s[k].every(v=>v===0||v===1))&&Array.isArray(s.cabinets)&&s.cabinets.length===3&&s.cabinets.every(c=>Number.isFinite(c.x)&&Number.isFinite(c.y)&&c.x>=55&&c.x<=840&&c.y>=75&&c.y<=590&&typeof c.stored==='boolean')&&['palette','wall','cabinet'].every(k=>Number.isInteger(s[k])&&s[k]>=0&&s[k]<4)&&Array.isArray(s.wires)&&s.wires.length===6&&s.wires.every(v=>Number.isInteger(v)&&v>=0&&v<4)&&typeof s.repaired==='boolean'&&typeof s.returned==='boolean'&&Number.isFinite(s.best)&&s.best>=0;}
 function progress(s){if(s.stage===0)return s.cabinets.filter(c=>c.stored).length/3;if(s.stage<=3){let a=s[['','dust','grime','floor'][s.stage]];return a.reduce((n,v)=>n+(s.stage===3?v:1-v),0)/153;}return s.stage===7?1:0;}
 function advance(s){if(s.stage<4&&progress(s)>=1)s.stage++;}
 function move(s,i,x,y){if(s.stage!==0&&!(s.stage===6&&i===0))return false;const c=s.cabinets[i];if(s.stage===0&&x>540&&y<215){c.x=595+i*100;c.y=185;c.stored=true;}else if(s.stage===6&&x<760&&y>280){c.x=Math.max(110,Math.min(740,x));c.y=Math.max(310,Math.min(560,y));c.stored=false;s.returned=true;s.stage=7;}else return false;advance(s);return true;}
 function brush(s,x,y){if(s.stage<1||s.stage>3)return 0;const stage=s.stage,key=['','dust','grime','floor'][stage];let changed=0;for(let i=0;i<153;i++){const cx=110+(i%17)*40,cy=280+Math.floor(i/17)*40;if(Math.hypot(cx-x,cy-y)<(stage===1?58:65)&&s[key][i]!== (stage===3?1:0)){s[key][i]=stage===3?1:0;changed++;}}advance(s);return changed;}
 function connected(s){return s.wires.every((v,i)=>v===solution[i]);}
 function repair(s){if(s.stage===5&&connected(s)){s.repaired=true;s.stage=6;return true;}return false;}
 return {fresh,valid,progress,move,brush,connected,repair,colors,solution};
})();
if(typeof module!=='undefined')module.exports=Arcade;
if(typeof document!=='undefined')(()=>{
 const $=id=>document.getElementById(id),canvas=$('room'),ctx=canvas.getContext('2d'),KEY='afterhours.room.v1';let state=Arcade.fresh(),storage=true;
 try{let old=JSON.parse(localStorage.getItem(KEY));if(Arcade.valid(old))state=old;}catch{storage=false;}
 const titles=['Make a little room.','A clean sweep.','Under all that grime.','A floor worth dancing on.','Give the walls a future.','Follow the signal.','Bring it home.','A little light again.'];
 const descriptions=['Three silent cabinets. Years of dust. Wheel each machine into an outlined bay in the back room to reveal the floor.','Hold and drag the broom across the loose debris. There might still be something worth finding.','The debris is gone. Work the scrubber over the dark patches to uncover the old floor.','Choose a finish, then drag the roller across the floor to lay it down. You can change your palette later.','Choose a wall finish to tie the room together. The old stripes have had a good run.','Star Signal has one broken circuit. Open the workbench, reconnect its modules, and listen for the first boot.','Your first machine works. Wheel Star Signal out of storage and place it anywhere on the restored floor.','You did this. Play your restored machine, try another color scheme, and enjoy the room. The rest of the arcade is waiting.'];
 const hints=['Drag each cabinet into the BACK STORAGE bays · or use the journal buttons.','Hold & sweep across the floor · Arrows + Space also work.','Hold & scrub the dark patches · Arrows + Space also work.','Pick a palette, then hold & roll over the floor.','Try a finish in the journal, then apply it.','Open the workbench to repair Star Signal.','Drag Star Signal onto the main floor · or use Place cabinet.','Click the glowing cabinet to play · customize freely in the journal.'];
 const steps=['Clear the floor','Sweep loose debris','Scrub the grime','Restore the floor','Paint the walls','Repair Star Signal','Place your first game'];
 const palettes=[['Midnight terrazzo','#233a4c','#d6b59d'],['Candy checker','#b76d85','#e7c7b3'],['Seaside tiles','#55918b','#e3cf9d'],['Amber parquet','#8e6248','#c49361']];
 let pointer={x:450,y:460},held=false,drag=-1,keys=new Set(),last=0,toastTime=0,particles=[],sound=false,audio=null,lastChime=0,saveTimer=0,wallPreview=state.wall;
 function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save').textContent='Saved locally';}catch{storage=false;$('save').textContent='Session only · storage unavailable';}}
 function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(save,200);}
 function tone(freq=500){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.18);}catch{}}
 function toast(message){$('toast').textContent=message;$('toast').style.opacity=1;toastTime=performance.now()+3600;}
 function button(text,fn,primary=false){const b=document.createElement('button');b.textContent=text;b.className=primary?'primary':'';b.onclick=fn;return b;}
 function swatches(label,key,names,colors){const l=document.createElement('label');l.textContent=label;$('actions').append(l);const row=document.createElement('div');row.className='swatches';names.forEach((name,i)=>{let b=button(name,()=>{if(key==='wall'&&state.stage===4)wallPreview=i;else state[key]=i;renderUI();queueSave();});b.style.setProperty('--swatch',colors[i]);b.setAttribute('aria-pressed',String((key==='wall'&&state.stage===4?wallPreview:state[key])===i));row.append(b);});$('actions').append(row);}
 function renderUI(){const s=state.stage;$('title').textContent=titles[s];$('description').textContent=descriptions[s];$('hint').textContent=hints[s];$('progress').style.width=Arcade.progress(state)*100+'%';$('count').textContent=s===0?`${state.cabinets.filter(c=>c.stored).length} / 3 cabinets in storage`:s<=3?`${Math.round(Arcade.progress(state)*100)}% ${['','swept','scrubbed','restored'][s]}`:s===7?'FIRST CORNER RESTORED · 100%':`STEP ${s+1} OF 7`;$('actions').replaceChildren();
 if(s===0)state.cabinets.forEach((c,i)=>{if(!c.stored)$('actions').append(button(`Wheel ${['Star Signal','Moon Rally','Pixel Garden'][i]} to storage`,()=>{Arcade.move(state,i,650,155);changed();}));});
 if(s===3||s===7)swatches('FLOOR FINISH','palette',palettes.map(p=>p[0]),palettes.map(p=>p[1]));
 if(s===4||s===7){swatches('WALL FINISH','wall',['Deep teal','Rose dusk','Warm cream','Ink blue'],['#35545c','#744959','#c5ae89','#354564']);if(s===4)$('actions').append(button('Paint the walls',()=>{state.wall=wallPreview;state.stage=5;tone(660);toast('A new coat. A new beginning.');changed();},true));}
 if(s>=5)swatches('STAR SIGNAL · CABINET COLOR','cabinet',['Mint','Rose','Honey','Lilac'],Arcade.colors);
 if(s===5)$('actions').append(button('Open repair workbench',openRepair,true));if(s===6)$('actions').append(button('Place Star Signal on the floor',()=>{Arcade.move(state,0,420,390);changed();},true));if(s===7)$('actions').prepend(button('Play Star Signal ↗',openGame,true));
 $('journal').replaceChildren();steps.forEach((v,i)=>{const li=document.createElement('li');li.className=i<s?'done':i===s?'current':'';li.innerHTML=`<span>${i<s?'✓':String(i+1).padStart(2,'0')}</span>${v}`;$('journal').append(li);});if(!storage)$('save').textContent='Session only · storage unavailable';}
 let previousStage=state.stage;
 function changed(){if(previousStage!==state.stage){const messages=['','Room to breathe. Broom unlocked.','Found: a brass arcade token. Keep it for later.','Scrubber put away. Floor finishes unlocked.','The floor is yours. Time for the walls.','','It lives! Bring Star Signal back to the floor.','The first light is on. Welcome back.'];toast(messages[state.stage]||titles[state.stage]);tone(400+state.stage*100);previousStage=state.stage;held=false;keys.clear();drag=-1;}renderUI();queueSave();}
 function point(e,c=canvas){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height};}
 function work(x,y){let stage=state.stage,n=Arcade.brush(state,x,y);if(n){for(let i=0;i<Math.min(n*2,12);i++)particles.push({x,y,vx:(Math.random()-.5)*90,vy:-30-Math.random()*60,t:.55,color:stage===1?'#d3b68b':stage===2?'#b3dedc':'#f0d1b2'});if(performance.now()-lastChime>110){tone(stage===1?180:stage===2?280:420);lastChime=performance.now();}changed();}}
 function segment(a,b){const dist=Math.hypot(b.x-a.x,b.y-a.y),n=Math.max(1,Math.ceil(dist/15)),stage=state.stage;for(let i=1;i<=n&&state.stage===stage;i++)work(a.x+(b.x-a.x)*i/n,a.y+(b.y-a.y)*i/n);}
 canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.focus();keys.clear();pointer=point(e);held=true;canvas.setPointerCapture(e.pointerId);if(state.stage===0||state.stage===6){drag=state.cabinets.findLastIndex((c,i)=>Math.abs(c.x-pointer.x)<48&&pointer.y>c.y-115&&pointer.y<c.y+24&&(state.stage===0?!c.stored:i===0));}else if(state.stage===7){const c=state.cabinets[0];if(Math.abs(c.x-pointer.x)<55&&Math.abs(c.y-pointer.y)<120)openGame();}else work(pointer.x,pointer.y);};
 canvas.onpointermove=e=>{const p=point(e),old=pointer;pointer=p;if(e.movementX||e.movementY)keys.clear();if(held&&drag<0)segment(old,p);};
 canvas.onpointerup=e=>{if(drag>=0){if(!Arcade.move(state,drag,pointer.x,pointer.y))toast(state.stage===0?'Drop inside a dashed storage bay at the back.':'Place the cabinet on the restored floor.');changed();}held=false;drag=-1;};
 function release(){held=false;drag=-1;keys.clear();}canvas.onpointercancel=release;canvas.onlostpointercapture=release;window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{release();if(document.hidden){mini.running=false;updateGameStatus('Paused · press Play to start a new round.');save();}});
 canvas.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key)){e.preventDefault();held=false;drag=-1;keys.add(e.key);}};canvas.onkeyup=e=>keys.delete(e.key);canvas.onblur=release;
 $('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));tone();};
 $('reset').onclick=()=>{$('resetConfirm').hidden=false;};$('cancelReset').onclick=()=>{$('resetConfirm').hidden=true;};$('confirmReset').onclick=()=>{state=Arcade.fresh();wallPreview=0;previousStage=0;release();$('resetConfirm').hidden=true;changed();toast('A fresh start.');};
 function openRepair(){release();renderWires();$('repair').showModal();}function renderWires(){let row=$('wires');row.replaceChildren();state.wires.forEach((rot,i)=>{const b=button('',()=>{state.wires[i]=(rot+1)%4;renderWires();row.children[i].focus();queueSave();tone(260);});b.setAttribute('aria-label',`Connector ${i+1}, rotation ${rot*90} degrees. Rotate clockwise`);b.innerHTML=`<svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="33" fill="#202f40"/><path d="M50 0 V50 H100" fill="none" stroke="#9ee0c3" stroke-width="10" stroke-linejoin="round" transform="rotate(${rot*90} 50 50)"/><circle cx="50" cy="50" r="7" fill="#e6d3af"/></svg>`;row.append(b);});}
 $('closeRepair').onclick=()=>$('repair').close();$('wireHint').onclick=()=>{$('circuitStatus').textContent='Follow this route: input → down → right → up → right → down → output. Rotate each elbow to join its neighbors.';};$('testCircuit').onclick=()=>{if(Arcade.repair(state)){$('repair').close();changed();}else{$('circuitStatus').textContent='No signal yet. Check that both ends of every connector meet the route. Try the hint if you get stuck.';tone(110);}};
 function rect(x,y,w,h,c,r=0){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}function text(t,x,y,size=12,color='#e6ddcf',align='left'){ctx.fillStyle=color;ctx.font=`${size}px system-ui`;ctx.textAlign=align;ctx.fillText(t,x,y);}
 function cabinet(c,i,x=c.x,y=c.y){const col=i===0?Arcade.colors[state.cabinet]:i===1?'#c78e60':'#8d84ad',on=i===0&&state.repaired;ctx.save();ctx.translate(x,y);if(c.stored&&drag!==i)ctx.scale(.72,.72);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(8,15,49,18,0,0,7);ctx.fill();if(on){const glow=ctx.createRadialGradient(0,-40,5,0,-40,120);glow.addColorStop(0,'#85ecd230');glow.addColorStop(1,'#85ecd200');ctx.fillStyle=glow;ctx.fillRect(-130,-150,260,250);}rect(-37,-108,74,120,col,4);rect(37,-100,11,110,'#263345');rect(-30,-100,60,19,'#172232',2);text(['STAR SIGNAL','MOON RALLY','PIXEL GARDEN'][i],0,-87,7,on?'#b5ffdc':'#c3b8ae','center');rect(-30,-77,60,51,'#151e2a',4);rect(-24,-71,48,36,on?'#173f50':'#26323d',3);if(on){text('✦',0,-46,25,'#b4f5d9','center');}else{ctx.strokeStyle='#667076';ctx.beginPath();ctx.moveTo(-17,-41);ctx.lineTo(15,-64);ctx.stroke();}rect(-37,-23,74,18,'#354252',2);rect(-18,-21,4,12,'#151b26');rect(-22,-23,12,7,col,4);rect(10,-19,7,7,'#dfb568',4);rect(23,-16,7,7,'#d18ba0',4);rect(-23,0,46,6,'#202c3a');rect(-5,1,10,3,'#a7a6a2');rect(-27,11,10,5,'#111926');rect(20,11,10,5,'#111926');if(!state.repaired||i!==0){ctx.globalAlpha=.35;rect(-35,-105,69,3,'#eadfc6');rect(-28,-3,17,2,'#eadfc6');}ctx.restore();}
 function draw(dt,now){ctx.clearRect(0,0,900,660);rect(0,0,900,660,'#171e2a');rect(34,44,832,578,'#0d1420',12);rect(50,56,800,180,state.stage<4?'#514951':['#35545c','#744959','#c5ae89','#354564'][state.stage===4?wallPreview:state.wall]);
 for(let x=60;x<850;x+=24)rect(x,56,2,171,'#ffffff06');rect(50,201,800,8,state.stage<5?'#80645f':'#e7bbaa');rect(50,213,800,14,'#26313f');rect(50,233,800,382,'#38404a');
 rect(538,61,306,160,'#222a35',5);rect(548,71,286,25,'#313b47',3);text('BACK STORAGE / WORKSHOP',691,88,11,'#b3b2a7','center');for(let i=0;i<3;i++){ctx.setLineDash([5,5]);ctx.strokeStyle='#667e79';ctx.strokeRect(551+i*100,108,88,99);ctx.setLineDash([]);text(String(i+1).padStart(2,'0'),595+i*100,202,9,'#879b92','center');}
 rect(96,79,246,82,'#222c3a',5);ctx.shadowColor=state.stage===7?'#ec9ba8':'transparent';ctx.shadowBlur=state.stage===7?18:0;text('AFTER HOURS',219,117,25,state.stage===7?'#efb1ba':'#8d777c','center');ctx.shadowBlur=0;text('GOOD TIMES, ONCE AGAIN.',219,141,9,'#b7a699','center');rect(375,98,95,71,'#aa906d',2);rect(381,104,83,59,'#283a44');text('GRAND',422,124,12,'#d4c39e','center');text('REOPENING',422,142,11,'#d4c39e','center');text('SOON',422,155,8,'#a2b9b2','center');
 for(let i=0;i<153;i++){const x=90+i%17*40,y=260+Math.floor(i/17)*40,p=palettes[state.palette],checker=(i%17+Math.floor(i/17))%2;rect(x,y,39,39,state.floor[i]?(checker?p[1]:p[2]):(checker?'#72665d':'#928276'));if(state.floor[i]){if(state.palette===0){for(let j=0;j<5;j++)rect(x+((i*7+j*11)%35),y+((i*13+j*7)%35),3,2,j%2?'#da9eab':'#87b4ae');}if(state.palette===3){rect(x+4,y+12,31,1,'#694c3a');rect(x+4,y+27,31,1,'#694c3a');}}if(state.grime[i]){rect(x+1,y+1,38,38,'#28282580',7);rect(x+7,y+9,23,16,'#39352d70',9);}if(state.dust[i]){for(let j=0;j<3;j++){ctx.save();ctx.translate(x+7+(i*7+j*13)%29,y+6+(i*11+j*9)%28);ctx.rotate(i+j);rect(-5,-2,10,4,['#b69b74','#c5b594','#777c79'][j],1);ctx.restore();}}}
 if(state.stage===0){for(let c of state.cabinets)if(!c.stored){ctx.strokeStyle='#c7ba9625';ctx.strokeRect(c.x-44,c.y-110,90,132);}}
 rect(50,610,800,12,'#283442');text('FRONT ROOM',75,645,10,'#7b8b99');text(state.stage===7?'FIRST CORNER RESTORED':'RESTORATION IN PROGRESS',827,645,10,state.stage===7?'#9ee0c3':'#7b8b99','right');
 state.cabinets.map((c,i)=>({c,i})).sort((a,b)=>a.c.y-b.c.y).forEach(({c,i})=>{if(i!==drag)cabinet(c,i);});if(drag>=0){ctx.globalAlpha=.85;cabinet(state.cabinets[drag],drag,pointer.x,pointer.y);ctx.globalAlpha=1;}
 if(state.stage>=1&&state.stage<=3){ctx.save();ctx.translate(pointer.x,pointer.y);ctx.fillStyle='#b7efd21b';ctx.beginPath();ctx.arc(0,0,state.stage===1?58:65,0,7);ctx.fill();ctx.strokeStyle='#c9efd07a';ctx.setLineDash([3,7]);ctx.stroke();ctx.setLineDash([]);rect(-3,-65,6,65,'#b69470',3);rect(-28,-6,56,13,state.stage===1?'#cdad74':state.stage===2?'#8cc7c1':palettes[state.palette][1],4);if(state.stage===1){for(let i=-25;i<28;i+=5)rect(i,6,3,12,'#af8858');}ctx.restore();}
 particles=particles.filter(p=>p.t>0);for(let p of particles){p.t-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;ctx.globalAlpha=Math.max(0,p.t/.55);rect(p.x,p.y,4,4,p.color,2);}ctx.globalAlpha=1;if(now>toastTime)$('toast').style.opacity=0;}
 const mini={running:false,x:270,stars:[],score:0,time:0,spawn:0,left:false,right:false,round:0},mc=$('minigame'),mg=mc.getContext('2d');
 function updateGameStatus(v){$('gameStatus').textContent=v;}function openGame(){release();mini.running=false;$('arcade').showModal();updateGameStatus(`Best: ${state.best} stars · Ready when you are.`);mc.focus();}function stopGame(){mini.running=false;mini.left=mini.right=false;} $('closeArcade').onclick=()=>{stopGame();$('arcade').close();};$('arcade').addEventListener('close',stopGame);
 $('startGame').onclick=()=>{Object.assign(mini,{running:true,x:270,stars:[],score:0,time:30,spawn:0,left:false,right:false,round:mini.round+1});mc.focus();};mc.onpointermove=e=>{mini.x=Math.max(22,Math.min(518,point(e,mc).x));mini.left=mini.right=false;};mc.onpointerdown=mc.onpointermove;mc.onkeydown=e=>{if(e.key.startsWith('Arrow')){e.preventDefault();if(e.key==='ArrowLeft')mini.left=true;if(e.key==='ArrowRight')mini.right=true;}};mc.onkeyup=e=>{if(e.key==='ArrowLeft')mini.left=false;if(e.key==='ArrowRight')mini.right=false;};mc.onblur=()=>{mini.left=mini.right=false;};window.addEventListener('blur',()=>{if(mini.running){stopGame();updateGameStatus('Paused · press Play to start a new round.');}});
 function drawMini(dt){if(!$('arcade').open)return;mg.fillStyle='#0d1427';mg.fillRect(0,0,540,360);for(let i=0;i<40;i++){mg.fillStyle='#7188a870';mg.fillRect((i*97)%540,(i*53)%300,2,2);}if(mini.running){mini.time-=dt;mini.spawn-=dt;mini.x=Math.max(22,Math.min(518,mini.x+((mini.right?1:0)-(mini.left?1:0))*380*dt));if(mini.spawn<=0){mini.stars.push({x:35+Math.random()*470,y:-10});mini.spawn=.65;}for(let s of mini.stars){s.y+=130*dt;if(s.y>309&&s.y<340&&Math.abs(s.x-mini.x)<32){s.y=400;mini.score++;tone(700+mini.score*12);}}mini.stars=mini.stars.filter(s=>s.y<370);updateGameStatus(`${mini.score} / 12 stars · ${Math.max(0,Math.ceil(mini.time))}s`);if(mini.time<=0){mini.running=false;state.best=Math.max(state.best,mini.score);queueSave();updateGameStatus(mini.score>=12?`Constellation lit! ${mini.score} stars · Best ${state.best}`:`${mini.score} stars · Try for 12! Best ${state.best}`);}}
 mg.fillStyle='#f1dba3';mg.font='25px system-ui';mg.textAlign='center';for(let s of mini.stars)mg.fillText('✦',s.x,s.y);mg.fillStyle='#9ee0c3';mg.beginPath();mg.roundRect(mini.x-30,322,60,11,5);mg.fill();mg.fillStyle='#ec9ba8';mg.fillRect(mini.x-3,311,6,11);if(!mini.running){mg.fillStyle='#e8c9ad';mg.font='22px Georgia';mg.fillText(mini.score>=12?'THE STARS REMEMBER.':'STAR SIGNAL',270,158);mg.font='12px system-ui';mg.fillText('A small light in a room you saved.',270,188);}}
 function frame(now){const dt=Math.min((now-last)/1000||0,1/30);last=now;if(!document.hidden&&!$('repair').open&&!$('arcade').open){let dx=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0),dy=(keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0);if(dx||dy){const k=320*dt/Math.hypot(dx,dy);pointer.x=Math.max(90,Math.min(770,pointer.x+dx*k));pointer.y=Math.max(260,Math.min(620,pointer.y+dy*k));}if(keys.has(' '))work(pointer.x,pointer.y);}draw(dt,now);drawMini(dt);requestAnimationFrame(frame);}
 window.addEventListener('pagehide',save);renderUI();requestAnimationFrame(frame);
})();
